// Acuario CAPICÚA: criaturas marinas reales como mascotas cosméticas (no dan ventajas académicas).
// Cada ficha trae un dato verificable. El arte es procedural (SVG) por familia, así hay decenas de especies.

const S = (id, name, sci, art, v, colors, rarity, fact, power) => ({ id, name, sci, art, v, colors, rarity, fact, power });
export const RARITY = { comun: { name: 'Común', color: '#5fd3f0', w: 60 }, rara: { name: 'Rara', color: '#a78bfa', w: 28 }, epica: { name: 'Épica', color: '#ff2d7a', w: 10 }, legendaria: { name: 'Legendaria', color: '#ffc83a', w: 2 } };

export const SPECIES = [
  /* Babosas marinas (nudibranquios) */
  S('glaucus', 'Dragón azul', 'Glaucus atlanticus', 'nudi', 'dragon', ['#3b82f6', '#bfe9ff', '#1e3a8a'], 'epica', 'Flota en la superficie del mar y se alimenta de carabelas portuguesas, de las que reutiliza las células urticantes.', 'Escudo brillante: destella cuando aciertas.'),
  S('chromo-annae', 'Chromodoris de Anna', 'Chromodoris annae', 'nudi', 'plain', ['#2c4cff', '#ffd23a', '#ffffff'], 'comun', 'Como todos los nudibranquios, pierde la concha al hacerse adulto.', 'Aura azul tranquila.'),
  S('hypselodoris', 'Hypselodoris', 'Hypselodoris bullockii', 'nudi', 'plain', ['#7b3cf0', '#ff9a3a', '#ffffff'], 'comun', 'Sus colores vivos advierten a los depredadores de que no es buena comida.', 'Destello violeta.'),
  S('flabellina', 'Chal español', 'Flabellina iodinea', 'nudi', 'cerata', ['#7b3cf0', '#ff7a1a', '#ffd9b0'], 'rara', 'Sus apéndices naranjas (cerata) tienen forma de dedos y le ayudan a respirar.', 'Chispas naranjas.'),
  S('nembrotha', 'Nembrotha', 'Nembrotha cristata', 'nudi', 'cerata', ['#0f172a', '#22c55e', '#86efac'], 'comun', 'Se alimenta de ascidias (organismos filtradores) y acumula sus toxinas.', 'Brillo verde.'),
  S('phyllidia', 'Phyllidia', 'Phyllidia varicosa', 'nudi', 'bumpy', ['#64748b', '#ffd23a', '#f9a8d4'], 'comun', 'Su piel con protuberancias amarillas segrega sustancias de sabor desagradable.', 'Motas de colores.'),
  S('chromo-magnifica', 'Magnífica', 'Chromodoris magnifica', 'nudi', 'plain', ['#111827', '#3b82f6', '#fb923c'], 'rara', 'Es de las babosas marinas más fotografiadas por sus bandas azules y naranjas.', 'Rayas eléctricas.'),
  S('costasiella', 'Oveja del mar', 'Costasiella kuroshimae', 'nudi', 'sheep', ['#a7f3d0', '#16a34a', '#fef9c3'], 'epica', 'Retiene cloroplastos de las algas que come y puede hacer algo de fotosíntesis (cleptoplastia).', 'Se carga con la luz: más brillo cada día.'),
  S('spanish-dancer', 'Bailarina española', 'Hexabranchus sanguineus', 'nudi', 'dancer', ['#ef4444', '#fecaca', '#fb923c'], 'epica', 'Puede nadar ondulando los bordes de su cuerpo como las faldas de una bailarina.', 'Estela de baile.'),
  S('pteraeolidia', 'Dragón azul del Indo-Pacífico', 'Pteraeolidia ianthina', 'nudi', 'cerata', ['#1d4ed8', '#7dd3fc', '#bae6fd'], 'rara', 'Alberga algas simbiontes en sus apéndices, que le dan color y energía.', 'Reflejo marino.'),
  /* Pulpos */
  S('vulgaris', 'Pulpo común', 'Octopus vulgaris', 'octo', 'plain', ['#e07a5f', '#f4a261', '#fff1e6'], 'comun', 'Tiene tres corazones y sangre azul con hemocianina.', 'Tres corazones: tres destellos por acierto.'),
  S('blue-ring', 'Pulpo de anillos azules', 'Hapalochlaena lunulata', 'octo', 'rings', ['#f2c94c', '#2563eb', '#fef08a'], 'epica', 'Es pequeño pero su veneno (tetrodotoxina) es muy peligroso: se admira de lejos.', 'Anillos de luz azul.'),
  S('dumbo', 'Pulpo Dumbo', 'Grimpoteuthis sp.', 'octo', 'dumbo', ['#fbcfe8', '#f472b6', '#ffe4f1'], 'rara', 'Vive en el fondo del mar y nada moviendo unas aletas que parecen orejas.', 'Orejas voladoras.'),
  S('giant-pacific', 'Pulpo gigante del Pacífico', 'Enteroctopus dofleini', 'octo', 'plain', ['#c2410c', '#fdba74', '#fff7ed'], 'epica', 'Es la especie de pulpo más grande conocida.', 'Tamaño máximo en la pantalla.'),
  S('mimic', 'Pulpo mimético', 'Thaumoctopus mimicus', 'octo', 'stripes', ['#f5deb3', '#3b2a1a', '#d6b78a'], 'epica', 'Imita el aspecto y los movimientos de otros animales marinos para engañar a los depredadores.', 'Cambia de forma en cada combate.'),
  S('blanket', 'Pulpo cobija', 'Tremoctopus sp.', 'octo', 'blanket', ['#7c3aed', '#f9a8d4', '#fcd34d'], 'legendaria', 'Las hembras son enormes comparadas con los machos, que miden pocos centímetros.', 'Capa de colores.'),
  S('coconut', 'Pulpo del coco', 'Amphioctopus marginatus', 'octo', 'coconut', ['#b45309', '#fcd34d', '#78350f'], 'rara', 'Recoge cáscaras de coco y las usa como refugio: un caso célebre de uso de herramientas.', 'Refugio portátil.'),
  S('wunderpus', 'Wunderpus', 'Wunderpus photogenicus', 'octo', 'stripes', ['#a16207', '#fff7ed', '#7c2d12'], 'rara', 'Sus patrones de rayas son únicos en cada individuo.', 'Rayas hipnóticas.'),
  S('glass-octo', 'Pulpo de cristal', 'Vitreledonella richardi', 'octo', 'glass', ['#bae6fd', '#e0f2fe', '#7dd3fc'], 'legendaria', 'Su cuerpo es casi transparente: se ve a través de él.', 'Atraviesa las dudas: pistas más claras.'),
  /* Peces */
  S('clown', 'Pez payaso', 'Amphiprion ocellaris', 'fish', 'clown', ['#ff7a1a', '#ffffff', '#1a1150'], 'comun', 'Vive entre los tentáculos de las anémonas sin ser dañado y todos nacen machos.', 'Sonrisa contagiosa.'),
  S('mandarin', 'Pez mandarín', 'Synchiropus splendidus', 'fish', 'mandarin', ['#2563eb', '#ff7a1a', '#22c55e'], 'rara', 'Cubierto de una capa de mucosidad con mal sabor, ahuyenta a los depredadores.', 'Mosaico mágico.'),
  S('lion', 'Pez león', 'Pterois volitans', 'fish', 'lion', ['#b91c1c', '#fef3c7', '#78350f'], 'rara', 'Sus espinas son venenosas; en el Atlántico y el Caribe es especie invasora.', 'Abanico de espinas.'),
  S('angler', 'Rape abisal', 'Lophiiformes', 'fish', 'angler', ['#1f2937', '#fde047', '#6b7280'], 'epica', 'Muchas especies atraen presas con un señuelo luminoso producido por bacterias.', 'Linterna: ilumina la pista 1.'),
  S('blobfish', 'Pez gota', 'Psychrolutes marcidus', 'fish', 'blob', ['#f9a8d4', '#fbcfe8', '#be185d'], 'rara', 'Su aspecto "derretido" se debe a la despresurización al sacarlo del fondo; en el agua se ve normal.', 'Cara de ánimo suave.'),
  S('mola', 'Pez luna', 'Mola mola', 'fish', 'sunfish', ['#94a3b8', '#cbd5e1', '#475569'], 'epica', 'Es el pez óseo más pesado conocido.', 'Gigante plácido.'),
  S('boxfish', 'Pez cofre', 'Ostracion cubicus', 'fish', 'box', ['#fde047', '#1d4ed8', '#fff'], 'comun', 'Su cuerpo está protegido por placas óseas fusionadas, como una caja.', 'Caja de dados.'),
  S('puffer', 'Pez globo', 'Tetraodontidae', 'fish', 'puffer', ['#fde68a', '#78350f', '#fff7ed'], 'comun', 'Se hincha tragando agua para parecer más grande; muchas especies contienen tetrodotoxina.', 'Se infla de orgullo.'),
  S('parrot', 'Pez loro', 'Scaridae', 'fish', 'parrot', ['#22d3ee', '#f472b6', '#facc15'], 'comun', 'Muerde coral con su "pico" y produce arena; algunas especies duermen dentro de un capullo de mucosidad.', 'Colores del arcoíris.'),
  S('butterfly', 'Pez mariposa', 'Chaetodontidae', 'fish', 'angel', ['#fde047', '#1a1150', '#ffffff'], 'comun', 'Muchas especies forman parejas que nadan juntas durante años.', 'Alas de colores.'),
  S('emperor-angel', 'Pez ángel emperador', 'Pomacanthus imperator', 'fish', 'angel', ['#1d4ed8', '#fde047', '#f8fafc'], 'rara', 'Los juveniles tienen un patrón de anillos azules muy distinto al de los adultos.', 'Halo imperial.'),
  S('queen-angel', 'Pez ángel reina', 'Holacanthus ciliaris', 'fish', 'angel', ['#3b82f6', '#facc15', '#22d3ee'], 'rara', 'Lleva una "corona" azul en la frente y vive en arrecifes del Atlántico occidental.', 'Corona azul.'),
  S('royal-angel', 'Pez ángel real', 'Pygoplites diacanthus', 'fish', 'angel', ['#f97316', '#2563eb', '#f8fafc'], 'rara', 'Habita arrecifes del Indo-Pacífico y es famoso por sus rayas azules y naranjas.', 'Rayas reales.'),
  S('mudskipper', 'Pez fango', 'Periophthalmus', 'mud', 'plain', ['#78716c', '#fde68a', '#57534e'], 'rara', 'Puede pasar tiempo fuera del agua en el lodo, respirando en parte a través de la piel.', 'Salta obstáculos del lodo.'),
  S('oarfish', 'Pez remo', 'Regalecus glesne', 'ribbon', 'plain', ['#cbd5e1', '#ef4444', '#94a3b8'], 'legendaria', 'Es el pez óseo más largo conocido y vive en aguas profundas.', 'Cinta plateada.'),
  S('whale-shark', 'Tiburón ballena', 'Rhincodon typus', 'fish', 'whale', ['#475569', '#e2e8f0', '#1e293b'], 'epica', 'Es el pez más grande del mundo y se alimenta filtrando plancton.', 'Gigante amable.'),
  S('manta', 'Mantarraya gigante', 'Mobula birostris', 'ray', 'plain', ['#1f2937', '#f8fafc', '#475569'], 'epica', 'Tiene uno de los cerebros más grandes entre los peces y se alimenta filtrando plancton.', 'Vuelo submarino.'),
  S('seahorse', 'Caballito de mar', 'Hippocampus', 'horse', 'plain', ['#fbbf24', '#f59e0b', '#fff7ed'], 'comun', 'El macho incuba los huevos en una bolsa y da a luz a las crías.', 'Abrazo de cola.'),
  S('leafy', 'Dragón de mar foliado', 'Phycodurus eques', 'horse', 'leafy', ['#65a30d', '#fde047', '#166534'], 'legendaria', 'Es pariente del caballito de mar y se camufla como un alga flotante.', 'Camuflaje de algas.'),
  /* Medusas */
  S('moon-jelly', 'Medusa luna', 'Aurelia aurita', 'jelly', 'moon', ['#e0e7ff', '#a5b4fc', '#c7d2fe'], 'comun', 'Se reconoce por los cuatro círculos de su campana: son sus gónadas.', 'Luz lunar.'),
  S('lions-mane', 'Medusa melena de león', 'Cyanea capillata', 'jelly', 'mane', ['#ea580c', '#fb923c', '#7c2d12'], 'rara', 'Es una de las medusas más grandes y sus tentáculos pueden superar los 30 metros.', 'Melena dorada.'),
  S('box-jelly', 'Medusa caja', 'Chironex fleckeri', 'jelly', 'box', ['#a5f3fc', '#22d3ee', '#cffafe'], 'rara', 'Tiene 24 ojos de cuatro tipos y es muy venenosa.', 'Vigilante de 24 ojos.'),
  S('immortal', 'Medusa inmortal', 'Turritopsis dohrnii', 'jelly', 'tiny', ['#f0abfc', '#e879f9', '#fae8ff'], 'legendaria', 'Puede volver a su fase de pólipo y reiniciar su ciclo de vida en algunas circunstancias.', 'Segunda oportunidad: curita extra al día.'),
  S('crystal-jelly', 'Medusa cristal', 'Aequorea victoria', 'jelly', 'crystal', ['#bbf7d0', '#4ade80', '#dcfce7'], 'epica', 'De ella se aisló la proteína verde fluorescente (GFP), clave en biología (Nobel de Química 2008).', 'Brilla en verde.'),
  S('cassiopea', 'Medusa invertida', 'Cassiopea', 'jelly', 'upside', ['#86efac', '#16a34a', '#d9f99d'], 'rara', 'Descansa boca abajo en el fondo y alberga algas simbiontes que le dan color.', 'Mundo al revés.'),
  S('pelagia', 'Medusa luminosa', 'Pelagia noctiluca', 'jelly', 'glow', ['#c084fc', '#7c3aed', '#e9d5ff'], 'rara', 'Brilla en la oscuridad con bioluminiscencia.', 'Resplandor nocturno.'),
  S('fried-egg', 'Medusa huevo frito', 'Phacellophora camtschatica', 'jelly', 'egg', ['#fde68a', '#fbbf24', '#fef3c7'], 'rara', 'Su campana pálida con un centro amarillo recuerda a un huevo frito.', 'Desayuno luminoso.'),
  /* Otros */
  S('sea-angel', 'Ángel de mar', 'Clione limacina', 'angel2', 'plain', ['#bae6fd', '#fb7185', '#e0f2fe'], 'epica', 'Es un molusco transparente que "vuela" en aguas frías moviendo dos aletas parecidas a alas.', 'Alas translúcidas.'),
  S('yeti', 'Cangrejo yeti', 'Kiwa hirsuta', 'yeti', 'plain', ['#f8fafc', '#e2e8f0', '#fecaca'], 'epica', 'Vive cerca de fuentes hidrotermales y cultiva bacterias entre los pelos de sus pinzas.', 'Abrigo de felpa.'),
  S('nautilus', 'Nautilo', 'Nautilus pompilius', 'nautilus', 'plain', ['#f5deb3', '#b45309', '#fff7ed'], 'rara', 'Su concha en espiral está dividida en cámaras que usa para controlar la flotabilidad.', 'Espiral dorada.'),
  S('mantis', 'Camarón mantis', 'Odontodactylus scyllarus', 'mantis', 'plain', ['#22c55e', '#ef4444', '#3b82f6'], 'epica', 'Sus golpes son de los más rápidos del reino animal y su vista distingue muchos tipos de luz.', 'Golpe relámpago.'),
];
export const SPECIES_BY_ID = Object.fromEntries(SPECIES.map((s) => [s.id, s]));

/* ───── Arte procedural por familia ───── */
const eye = (x, y, r = 5) => `<circle cx="${x}" cy="${y}" r="${r}" fill="#fff"/><circle cx="${x + 1}" cy="${y + 0.5}" r="${r * 0.55}" fill="#1a1150"/><circle cx="${x + 2.2}" cy="${y - 1.2}" r="${r * 0.22}" fill="#fff"/>`;
const rnd = (seed) => { let a = seed >>> 0; return () => { a = (a * 1664525 + 1013904223) >>> 0; return a / 4294967296; }; };
const hash = (s) => [...s].reduce((h, c) => (h * 31 + c.charCodeAt(0)) >>> 0, 7);
const grad = (id, a, b) => `<linearGradient id="${id}" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${a}"/><stop offset="1" stop-color="${b}"/></linearGradient>`;

const FAM = {
  nudi(s, u) { const [c1, c2, c3] = s.colors; const r = rnd(hash(s.id)); let cer = '';
    const n = s.v === 'cerata' || s.v === 'dragon' || s.v === 'sheep' ? 14 : 5;
    for (let i = 0; i < n; i++) { const x = 40 + (i / n) * 120; const y = 74 + Math.sin(i) * 4; const L = s.v === 'dragon' ? 34 : s.v === 'sheep' ? 14 : 20; cer += `<path d="M${x} ${y + 8} q${-8 + r() * 16} ${-L} ${r() * 10 - 5} ${-L - 8}" stroke="${c2}" stroke-width="${s.v === 'sheep' ? 8 : 6}" stroke-linecap="round" fill="none"/><circle cx="${x + r() * 4}" cy="${y - L - 6}" r="${s.v === 'sheep' ? 5 : 3.5}" fill="${c3}"/>`; }
    const gills = s.v === 'plain' || s.v === 'dancer' ? `<g transform="translate(138 70)">${[...Array(6)].map((_, i) => `<path d="M0 0 q${Math.cos(i) * 14} ${-18 - i * 2} ${Math.cos(i * 1.7) * 18} -30" stroke="${c3}" stroke-width="5" fill="none" stroke-linecap="round"/>`).join('')}</g>` : '';
    const frill = s.v === 'dancer' ? `<path d="M30 104 q30 -22 70 -10 q40 -14 70 10 q-40 16 -70 12 q-30 4 -70 -12Z" fill="${c2}" opacity=".9" stroke="${c1}" stroke-width="3"/>` : '';
    const bumps = s.v === 'bumpy' ? [...Array(12)].map((_, i) => `<circle cx="${50 + i * 9}" cy="${92 + Math.sin(i) * 4}" r="${4 + (i % 3)}" fill="${c2}"/>`).join('') : '';
    const stripe = s.v === 'plain' ? `<path d="M40 100 q70 -18 130 0" stroke="${c2}" stroke-width="7" fill="none" stroke-linecap="round"/>` : '';
    return `${frill}<path d="M30 104 Q34 72 100 68 Q170 66 178 104 Q150 124 100 124 Q56 124 30 104Z" fill="${c1}"/>${stripe}${bumps}${cer}${gills}<path d="M42 84 q-14 -22 -4 -34 M60 76 q-12 -24 0 -36" stroke="${c2}" stroke-width="5" stroke-linecap="round" fill="none"/>${eye(48, 98, 4.5)}`; },
  octo(s, u) { const [c1, c2, c3] = s.colors; const r = rnd(hash(s.id)); const ten = [...Array(8)].map((_, i) => { const x = 54 + i * 13; const w = (r() - 0.5) * 18; return `<path class="tent" style="animation-delay:${i * 0.15}s" d="M${x} 108 q${w} 24 ${-w} 40 q${w * 1.4} 14 ${-w * 0.5} 26" stroke="${s.v === 'glass' ? c2 : c1}" stroke-width="${s.v === 'blanket' ? 5 : 9}" stroke-linecap="round" fill="none" ${s.v === 'glass' ? 'opacity=".55"' : ''}/>`; }).join('');
    const extra = { rings: [...Array(7)].map((_, i) => `<circle cx="${70 + (i % 4) * 22}" cy="${60 + Math.floor(i / 4) * 24}" r="6" fill="none" stroke="${c2}" stroke-width="3"/>`).join(''), stripes: [...Array(5)].map((_, i) => `<path d="M${64 + i * 18} 36 q4 36 -6 66" stroke="${c2}" stroke-width="6" fill="none"/>`).join(''), dumbo: `<ellipse cx="46" cy="64" rx="18" ry="10" fill="${c2}" transform="rotate(-24 46 64)"/><ellipse cx="154" cy="64" rx="18" ry="10" fill="${c2}" transform="rotate(24 154 64)"/>`, blanket: `<path d="M50 112 Q100 190 150 112 Q130 150 100 150 Q70 150 50 112Z" fill="${c2}" opacity=".6"/>`, coconut: `<path d="M60 136 q40 40 80 0 q-40 8 -80 0Z" fill="${c3}" stroke="#78350f" stroke-width="3"/>`, glass: `<circle cx="84" cy="70" r="7" fill="${c3}" opacity=".7"/><circle cx="116" cy="74" r="5" fill="${c3}" opacity=".7"/>`, plain: [...Array(9)].map((_, i) => `<circle cx="${70 + r() * 60}" cy="${38 + r() * 56}" r="${2 + r() * 3}" fill="${c3}" opacity=".6"/>`).join('') }[s.v] || '';
    return `${s.v === 'dumbo' ? extra : ''}${ten}<ellipse cx="100" cy="68" rx="52" ry="48" fill="${c1}" ${s.v === 'glass' ? 'opacity=".5" stroke="' + c2 + '" stroke-width="3"' : ''}/>${s.v === 'dumbo' ? '' : extra}${eye(82, 82, 8)}${eye(118, 82, 8)}`; },
  fish(s, u) { const [c1, c2, c3] = s.colors; const body = { clown: [100, 90, 56, 38], mandarin: [100, 90, 58, 34], lion: [96, 90, 50, 34], angler: [100, 96, 54, 46], blob: [100, 92, 58, 48], sunfish: [100, 90, 60, 60], box: [100, 92, 46, 40], puffer: [100, 92, 52, 50], parrot: [100, 90, 56, 40], angel: [100, 90, 40, 56], whale: [100, 94, 78, 40] }[s.v] || [100, 90, 56, 38]; const [cx, cy, rx, ry] = body;
    let deco = ''; if (s.v === 'clown') deco = [66, 100, 134].map((x, i) => `<path d="M${x - 5} ${cy - ry + 4} q${i === 1 ? 6 : 0} ${ry} 0 ${ry * 2 - 8}" stroke="${c2}" stroke-width="11" fill="none"/>`).join('');
    if (s.v === 'mandarin') deco = [...Array(8)].map((_, i) => `<path d="M${52 + i * 12} ${cy - 20 + (i % 2) * 20} q8 10 0 24" stroke="${i % 2 ? c2 : c3}" stroke-width="7" fill="none" stroke-linecap="round"/>`).join('');
    if (s.v === 'angel') deco = [...Array(5)].map((_, i) => `<path d="M${70 + i * 14} ${cy - 34 + Math.abs(i - 2) * 4} q4 34 0 68" stroke="${i % 2 ? c2 : c3}" stroke-width="6" fill="none"/>`).join('');
    if (s.v === 'lion') deco = [...Array(9)].map((_, i) => `<path d="M${60 + i * 9} ${cy - ry + 2} l${-14 + i} -34" stroke="${c2}" stroke-width="4" stroke-linecap="round"/>`).join('') + [...Array(5)].map((_, i) => `<path d="M${64 + i * 14} ${cy - 22} q4 22 0 44" stroke="${c3}" stroke-width="6" fill="none"/>`).join('');
    if (s.v === 'angler') deco = `<path d="M92 ${cy - ry + 4} q-6 -34 28 -34" stroke="${c3}" stroke-width="4" fill="none"/><circle cx="122" cy="${cy - ry - 30}" r="9" fill="${c2}" class="lure"/><path d="M52 ${cy + 8} l8 14 l8 -14 l8 14 l8 -14 l8 14" stroke="#fff" stroke-width="3" fill="none"/>`;
    if (s.v === 'puffer') deco = [...Array(14)].map((_, i) => { const a = (i / 14) * 6.283; return `<path d="M${cx + Math.cos(a) * rx} ${cy + Math.sin(a) * ry} l${Math.cos(a) * 10} ${Math.sin(a) * 10}" stroke="${c2}" stroke-width="3" stroke-linecap="round"/>`; }).join('');
    if (s.v === 'box') deco = [...Array(10)].map((_, i) => `<circle cx="${68 + (i % 5) * 16}" cy="${cy - 12 + Math.floor(i / 5) * 24}" r="4" fill="${c2}"/>`).join('');
    if (s.v === 'whale') deco = [...Array(22)].map((_, i) => `<circle cx="${50 + (i % 11) * 11}" cy="${cy - 10 + Math.floor(i / 11) * 22}" r="3" fill="${c2}"/>`).join('');
    if (s.v === 'parrot') deco = `<path d="M44 ${cy} q-8 8 0 14 q8 -2 10 -8Z" fill="#fff"/><path d="M70 ${cy - 24} q30 -14 60 0" stroke="${c2}" stroke-width="8" fill="none" stroke-linecap="round"/>`;
    const tail = `<path d="M${cx + rx - 4} ${cy} L${cx + rx + 34} ${cy - 28} Q${cx + rx + 20} ${cy} ${cx + rx + 34} ${cy + 28}Z" fill="${c3}" class="tail"/>`;
    const fin = s.v === 'sunfish' ? '' : `<path d="M${cx - 16} ${cy - ry} Q${cx} ${cy - ry - 26} ${cx + 28} ${cy - ry + 2}Z" fill="${c3}" opacity=".9"/>`;
    return `${tail}${fin}<ellipse cx="${cx}" cy="${cy}" rx="${rx}" ry="${ry}" fill="${c1}"/>${deco}<path d="M${cx - 10} ${cy + 14} q-16 12 -4 24 q12 -8 14 -22Z" fill="${c3}" opacity=".85"/>${eye(cx - rx + 18, cy - 8, s.v === 'blob' ? 6 : 7)}${s.v === 'blob' ? `<path d="M${cx - rx + 22} ${cy + 18} q14 10 30 2" stroke="#9d174d" stroke-width="4" fill="none" stroke-linecap="round"/><ellipse cx="${cx - rx + 8}" cy="${cy + 6}" rx="12" ry="9" fill="${c3}"/>` : ''}`; },
  jelly(s, u) { const [c1, c2, c3] = s.colors; const r = rnd(hash(s.id)); const n = s.v === 'mane' ? 16 : s.v === 'box' ? 4 : s.v === 'tiny' ? 5 : 9; const bell = s.v === 'box' ? `<path d="M52 82 L52 40 Q100 22 148 40 L148 82 Q100 94 52 82Z" fill="${c1}" opacity=".85"/>` : `<path d="M44 84 Q44 22 100 22 Q156 22 156 84 Q128 96 100 88 Q72 96 44 84Z" fill="${c1}" opacity=".88"/>`;
    const ten = [...Array(n)].map((_, i) => { const x = 56 + (i / (n - 1)) * 88; const L = (s.v === 'mane' ? 80 : s.v === 'moon' ? 34 : 62) + r() * 20; return `<path class="tent" style="animation-delay:${i * 0.12}s" d="M${x} 88 q${(r() - 0.5) * 24} ${L * 0.5} ${(r() - 0.5) * 16} ${L}" stroke="${i % 2 ? c2 : c3}" stroke-width="${s.v === 'mane' ? 3 : 4}" stroke-linecap="round" fill="none"/>`; }).join('');
    const marks = { moon: [...Array(4)].map((_, i) => `<circle cx="${80 + (i % 2) * 40 - 0}" cy="${52 + Math.floor(i / 2) * 14}" r="7" fill="none" stroke="${c2}" stroke-width="3"/>`).join(''), egg: `<circle cx="100" cy="60" r="16" fill="#f59e0b"/>`, crystal: [...Array(8)].map((_, i) => `<line x1="100" y1="64" x2="${100 + Math.cos(i * 0.785) * 50}" y2="${64 + Math.sin(i * 0.785) * 36}" stroke="${c2}" stroke-width="2" opacity=".6"/>`).join(''), glow: [...Array(10)].map(() => `<circle cx="${60 + r() * 80}" cy="${32 + r() * 44}" r="3" fill="#fff"/>`).join('') }[s.v] || '';
    const flip = s.v === 'upside' ? 'transform="rotate(180 100 100)"' : '';
    return `<g ${flip}><g class="bell">${bell}${marks}</g>${ten}</g>${s.v === 'upside' ? '' : eye(86, 54, 4) + eye(114, 54, 4)}`; },
  mud(s) { const [c1, c2, c3] = s.colors; return `<ellipse cx="100" cy="150" rx="88" ry="18" fill="#5b4636"/><path d="M30 130 Q40 96 100 96 Q150 96 170 118 L196 108 L188 134 Q150 152 100 148 Q56 146 30 130Z" fill="${c1}"/>${[...Array(8)].map((_, i) => `<circle cx="${60 + i * 12}" cy="${112 + (i % 3) * 6}" r="3" fill="${c2}"/>`).join('')}<path d="M76 98 Q100 70 130 98Z" fill="${c3}"/><circle cx="62" cy="94" r="10" fill="${c1}"/><circle cx="62" cy="92" r="6" fill="#fff"/><circle cx="63" cy="92" r="3" fill="#1a1150"/><circle cx="84" cy="90" r="10" fill="${c1}"/><circle cx="84" cy="88" r="6" fill="#fff"/><circle cx="85" cy="88" r="3" fill="#1a1150"/><path d="M52 122 l-16 14 l10 4Z" fill="${c1}"/>`; },
  ribbon(s) { const [c1, c2] = s.colors; const pts = [...Array(12)].map((_, i) => `${16 + i * 15},${100 + Math.sin(i * 0.9) * 26}`).join(' '); return `<polyline class="wiggle" points="${pts}" stroke="${c1}" stroke-width="14" fill="none" stroke-linecap="round" stroke-linejoin="round"/><path d="M26 96 q-10 -34 16 -48 M32 94 q0 -32 22 -42 M40 98 q10 -28 30 -34" stroke="${c2}" stroke-width="4" fill="none" stroke-linecap="round"/>${eye(26, 100, 6)}`; },
  ray(s) { const [c1, c2] = s.colors; return `<path d="M100 40 Q160 40 196 104 Q150 96 130 128 Q100 150 70 128 Q50 96 4 104 Q40 40 100 40Z" fill="${c1}"/><path d="M80 70 Q100 100 120 70 Q100 120 80 70Z" fill="${c2}"/><path d="M100 128 q4 40 -2 56" stroke="${c1}" stroke-width="6" fill="none" stroke-linecap="round"/><path d="M70 50 q-14 -10 -22 2 M130 50 q14 -10 22 2" stroke="${c1}" stroke-width="10" stroke-linecap="round" fill="none"/>${eye(86, 66, 4)}${eye(114, 66, 4)}`; },
  horse(s) { const [c1, c2, c3] = s.colors; const leafy = s.v === 'leafy'; const leaves = leafy ? [...Array(10)].map((_, i) => `<path d="M${88 + (i % 2) * 24} ${50 + i * 12} q${i % 2 ? 28 : -28} -10 ${i % 2 ? 36 : -36} 8 q${i % 2 ? -20 : 20} 14 ${i % 2 ? -36 : 36} -8Z" fill="${c2}" opacity=".85"/>`).join('') : '';
    return `${leaves}<path d="M110 30 Q80 30 78 56 Q76 76 96 90 Q112 104 100 128 Q88 150 108 164 Q130 176 140 156 Q124 160 120 148 Q130 128 122 108 Q148 86 130 52 Q126 36 110 30Z" fill="${c1}"/><path d="M78 56 L50 62 L56 70 L80 68Z" fill="${c1}"/><path d="M112 40 q22 -8 22 16 M118 60 q18 4 12 24" stroke="${c3}" stroke-width="5" fill="none" stroke-linecap="round"/>${[...Array(5)].map((_, i) => `<path d="M${98 + i * 3} ${74 + i * 18} q-10 4 -10 10" stroke="${c2}" stroke-width="3" fill="none"/>`).join('')}${eye(98, 48, 5)}`; },
  angel2(s) { const [c1, c2, c3] = s.colors; return `<g class="flap"><ellipse cx="62" cy="86" rx="38" ry="14" fill="${c3}" opacity=".7" transform="rotate(-26 62 86)"/><ellipse cx="138" cy="86" rx="38" ry="14" fill="${c3}" opacity=".7" transform="rotate(26 138 86)"/></g><path d="M80 52 Q100 30 120 52 Q130 90 100 150 Q70 90 80 52Z" fill="${c1}" opacity=".75"/><ellipse cx="100" cy="92" rx="12" ry="22" fill="${c2}" opacity=".85"/><circle cx="92" cy="50" r="3" fill="#1a1150"/><circle cx="108" cy="50" r="3" fill="#1a1150"/>`; },
  yeti(s) { const [c1, c2, c3] = s.colors; const hair = (x, y, dx) => [...Array(8)].map((_, i) => `<path d="M${x + i * 5 * dx} ${y} l${3 * dx} ${-8 - (i % 3) * 3}" stroke="${c2}" stroke-width="2.5" stroke-linecap="round"/>`).join(''); return `<path d="M60 100 q-34 -20 -26 -52 M140 100 q34 -20 26 -52" stroke="${c1}" stroke-width="14" fill="none" stroke-linecap="round"/><ellipse cx="34" cy="46" rx="16" ry="22" fill="${c1}"/><ellipse cx="166" cy="46" rx="16" ry="22" fill="${c1}"/>${hair(24, 50, 1)}${hair(150, 50, 1)}${[0, 1, 2].map((i) => `<path d="M${64 - i * 6} ${112 + i * 12} l-26 ${6 + i * 6} M${136 + i * 6} ${112 + i * 12} l26 ${6 + i * 6}" stroke="${c1}" stroke-width="7" stroke-linecap="round"/>`).join('')}<ellipse cx="100" cy="100" rx="46" ry="38" fill="${c1}"/><ellipse cx="100" cy="100" rx="34" ry="26" fill="${c2}" opacity=".6"/>${eye(86, 78, 5)}${eye(114, 78, 5)}`; },
  nautilus(s) { const [c1, c2, c3] = s.colors; return `<path d="M40 110 Q40 40 106 40 Q164 44 164 100 Q164 150 110 156 Q62 160 52 118 Q48 96 80 88 Q108 84 118 108 Q124 130 100 132" fill="${c1}" stroke="${c2}" stroke-width="5"/><path d="M76 56 Q100 70 100 100 M110 44 Q134 72 124 110 M146 56 Q156 90 138 128" stroke="${c2}" stroke-width="4" fill="none" opacity=".7"/>${[...Array(6)].map((_, i) => `<path class="tent" style="animation-delay:${i * 0.1}s" d="M${44 + i * 4} ${118 + i * 6} q-24 ${4 + i * 3} -30 ${14 + i * 2}" stroke="${c3}" stroke-width="5" stroke-linecap="round" fill="none"/>`).join('')}${eye(54, 112, 6)}`; },
  mantis(s) { const [c1, c2, c3] = s.colors; return `<path d="M60 110 Q100 80 150 110 Q180 120 186 146 Q150 150 100 140 Q64 140 60 110Z" fill="${c1}"/>${[0, 1, 2, 3, 4].map((i) => `<path d="M${72 + i * 18} 112 q4 14 0 28" stroke="${c2}" stroke-width="5" fill="none"/>`).join('')}<path d="M62 106 q-24 -8 -26 -30 q14 4 28 10Z" fill="${c3}" stroke="${c2}" stroke-width="3"/><path d="M60 114 q-26 4 -30 26 q16 -6 32 -12Z" fill="${c3}"/><path d="M76 98 q-6 -20 -2 -30 M92 96 q0 -22 6 -32" stroke="#1a1150" stroke-width="3" fill="none"/><circle cx="74" cy="64" r="9" fill="#ffd23a"/><circle cx="98" cy="62" r="9" fill="#ffd23a"/><circle cx="74" cy="64" r="4" fill="#1a1150"/><circle cx="98" cy="62" r="4" fill="#1a1150"/>`; },
};

let uidc = 0;
export function petSVG(id, { glow = true } = {}) {
  const s = SPECIES_BY_ID[id]; if (!s) return '';
  const body = FAM[s.art]?.(s, ++uidc) || '';
  return `<svg class="pet-svg" viewBox="0 0 200 200" role="img" aria-label="${s.name}" xmlns="http://www.w3.org/2000/svg">${glow ? `<defs><radialGradient id="pg${uidc}"><stop offset="0" stop-color="${s.colors[0]}" stop-opacity=".35"/><stop offset="1" stop-color="${s.colors[0]}" stop-opacity="0"/></radialGradient></defs><circle cx="100" cy="100" r="96" fill="url(#pg${uidc})"/>` : ''}<g class="pet-body">${body}</g></svg>`;
}

/** Sorteo con probabilidades PÚBLICAS (ver RARITY.w). Los duplicados dan PI. */
export function rollPet(rng = Math.random) {
  const total = Object.values(RARITY).reduce((a, r) => a + r.w, 0); let x = rng() * total; let rar = 'comun';
  for (const [k, r] of Object.entries(RARITY)) { if (x < r.w) { rar = k; break; } x -= r.w; }
  const pool = SPECIES.filter((s) => s.rarity === rar);
  return pool[Math.floor(rng() * pool.length)];
}
export const RARITY_ODDS = Object.entries(RARITY).map(([k, r]) => ({ k, name: r.name, pct: r.w }));
