// Enciclopedia CAPICÚA: entradas hechas a mano + entradas derivadas automáticamente de cada nivel, teorema y mentor.
// Incluye el buscador interno (lecciones, fórmulas, personajes, regiones, misiones, laboratorios, historia).
import { REGIONS, ALL_LEVELS } from './regions.js';
import { THEOREMS } from './theorems.js';
import { MENTORS } from './mentors.js';
import { SIDE_MISSIONS } from './game.js';
import { ERAS } from './history.js';

const E = (id, type, title, o) => ({ id, type, title, ...o });

export const EXTRA = [
  E('derivada', 'concepto', 'Derivada', { def: 'La derivada de una función en un punto mide cuán rápido cambia la función allí: es la pendiente de la recta tangente.', intuicion: 'Si f(t) es tu posición, f′(t) es tu velocidad en cada instante.', formula: "f'(a)=\\lim_{h\\to0}\\frac{f(a+h)-f(a)}{h}", simbolos: [["f′(a)", 'derivada de f en a'], ['h', 'incremento pequeño']], ejemplos: ['f(x) = x² → f′(x) = 2x. En x = 3 la pendiente es 6.'], historia: 'Newton y Leibniz (s. XVII) la desarrollaron de forma independiente; antes, Fermat usó ideas similares para máximos y mínimos y Madhava para series.', aplicaciones: ['Velocidad y aceleración', 'Optimización', 'Aprendizaje automático (descenso de gradiente)'], ejercicio: 'deriv_poly@1', relacionados: ['calculo.6', 'calculo.7', 'limite'] }),
  E('integral', 'concepto', 'Integral', { def: 'La integral acumula una cantidad: el área bajo una curva es la integral de la función.', intuicion: 'Suma de infinitas franjas muy finas. Si f es velocidad, ∫f es distancia recorrida.', formula: '\\int_a^b f(x)\\,dx', simbolos: [['∫', 'suma continua'], ['dx', 'ancho infinitesimal']], ejemplos: ['∫₀³ x² dx = 9'], historia: 'Arquímedes y Madhava calculaban áreas con sumas infinitas; Newton y Leibniz las unificaron con la derivada.', aplicaciones: ['Trabajo y energía', 'Probabilidad', 'Áreas y volúmenes'], ejercicio: 'definite_integral@1', relacionados: ['calculo.11', 'calculo.12', 'derivada'] }),
  E('limite', 'concepto', 'Límite', { def: 'El valor al que se acerca f(x) cuando x se acerca a un punto, sin tener que llegar a él.', intuicion: 'Como acercarte a una puerta: ¿qué valor “ves” al acercarte?', formula: '\\lim_{x\\to a}f(x)=L', simbolos: [['lím', 'límite'], ['x → a', 'x se acerca a a']], ejemplos: ['lím_{x→2} (x² − 4)/(x − 2) = 4'], historia: 'Cauchy y Weierstrass le dieron rigor en el s. XIX.', aplicaciones: ['Definir derivadas e integrales', 'Convergencia de algoritmos'], ejercicio: 'limit_factor', relacionados: ['calculo.2', 'calculo.3', 'derivada'] }),
  E('funcion', 'concepto', 'Función', { def: 'Una regla que asigna a cada entrada exactamente una salida.', intuicion: 'Una máquina: metes x, sale f(x).', formula: 'f: x \\mapsto f(x)', simbolos: [['f', 'nombre de la función'], ['x', 'entrada (variable independiente)'], ['f(x)', 'salida']], ejemplos: ['f(x) = 2x + 3; f(4) = 11.'], historia: 'Euler popularizó la notación f(x) (s. XVIII).', aplicaciones: ['Modelar relaciones: costo vs. cantidad', 'Programación'], ejercicio: 'func_eval@1', relacionados: ['algebra.13', 'calculo.1'] }),
  E('vector', 'concepto', 'Vector', { def: 'Un objeto con magnitud y dirección (en coordenadas, una lista ordenada de números).', intuicion: 'Una flecha: cuánto y hacia dónde.', formula: '\\vec v=(v_1,v_2,v_3)', simbolos: [['v⃗', 'vector'], ['vᵢ', 'componentes']], ejemplos: ['Velocidad (3, 4) m/s: rapidez 5 m/s.'], historia: 'Hamilton, Gibbs y Heaviside desarrollaron el cálculo vectorial en el s. XIX.', aplicaciones: ['Fuerzas', 'Gráficos 3D', 'IA (embeddings)'], ejercicio: 'vec_ops', relacionados: ['algebralineal.1', 'vectorial.1'] }),
  E('matriz', 'concepto', 'Matriz', { def: 'Una tabla rectangular de números. Puede representar datos o una transformación lineal.', intuicion: 'Una máquina que transforma vectores (girar, escalar, reflejar).', formula: 'A=\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}', simbolos: [['A', 'matriz 2×2'], ['aᵢⱼ', 'entrada de la fila i, columna j']], ejemplos: ['La matriz de rotación 90°: (0 −1; 1 0).'], historia: 'Cayley y Sylvester (s. XIX) la formalizaron; el método de eliminación aparece ya en Los nueve capítulos (China).', aplicaciones: ['Gráficos', 'Redes neuronales', 'Sistemas de ecuaciones'], ejercicio: 'mat_ops', relacionados: ['algebralineal.3', 'algebralineal.4'] }),
  E('probabilidad', 'concepto', 'Probabilidad', { def: 'Número entre 0 y 1 que mide qué tan posible es un suceso.', intuicion: 'Si repitieras el experimento muchas veces, ¿qué fracción de veces ocurriría?', formula: 'P(A)=\\frac{\\text{casos favorables}}{\\text{casos posibles}}', simbolos: [['P(A)', 'probabilidad del suceso A']], ejemplos: ['Sacar un 6 en un dado: 1/6.'], historia: 'Pascal y Fermat (1654) iniciaron la teoría con un problema de apuestas.', aplicaciones: ['Medicina', 'Seguros', 'Inteligencia artificial'], ejercicio: 'probability', relacionados: ['estadistica.8'] }),
  E('media', 'concepto', 'Media (promedio)', { def: 'Suma de los datos dividida entre la cantidad de datos.', intuicion: 'El valor “repartido en partes iguales”.', formula: '\\bar x=\\frac{1}{n}\\sum x_i', simbolos: [['x̄', 'media'], ['Σ', 'suma'], ['n', 'cantidad']], ejemplos: ['2, 4, 9 → media = 5.'], historia: '', aplicaciones: ['Notas', 'Ciencia de datos'], ejercicio: 'stat_central#media', relacionados: ['estadistica.3'] }),
  E('pi', 'constante', 'π (pi)', { def: 'La razón entre la circunferencia y el diámetro de cualquier círculo: ≈ 3,14159. Es irracional (e incluso trascendente).', intuicion: 'Si extiendes una circunferencia en línea recta, mide un poco más de tres diámetros.', formula: '\\pi=\\frac{C}{d}', simbolos: [['C', 'circunferencia'], ['d', 'diámetro']], ejemplos: ['Rueda de 1 m de diámetro: avanza ≈ 3,14 m por vuelta.'], historia: 'Babilonios, egipcios, Arquímedes, Liu Hui, Zu Chongzhi, Madhava y Al-Kashi mejoraron su valor durante milenios. Lambert demostró su irracionalidad en 1761 y Lindemann su trascendencia en 1882.', aplicaciones: ['Geometría', 'Ondas', 'Probabilidad', 'Física'], ejercicio: 'circle@1', relacionados: ['geometria.8', 'geometria.9'] }),
  E('e', 'constante', 'Número e', { def: 'Base de los logaritmos naturales: e ≈ 2,71828. La función eˣ es su propia derivada.', intuicion: 'El crecimiento continuo: la cantidad máxima a la que tiende el interés compuesto.', formula: 'e=\\lim_{n\\to\\infty}\\left(1+\\frac1n\\right)^n', simbolos: [['e', 'constante de Euler (≈ 2,718)']], ejemplos: ['d/dx eˣ = eˣ'], historia: 'Jacob Bernoulli lo observó con el interés compuesto (1683); Euler lo nombró y estudió.', aplicaciones: ['Crecimiento y decaimiento', 'Probabilidad', 'Física'], ejercicio: 'ode_sep', relacionados: ['edo.3'] }),
  E('i', 'constante', 'Unidad imaginaria i', { def: 'Número con i² = −1. Extiende los reales a los complejos.', intuicion: 'Un giro de 90° en el plano: aplicarlo dos veces da un giro de 180° (multiplicar por −1).', formula: 'i^2=-1', simbolos: [['i', 'unidad imaginaria'], ['a + bi', 'número complejo']], ejemplos: ['(1 + i)(1 − i) = 2'], historia: 'Cardano y Bombelli los usaron en el s. XVI al resolver cúbicas; Euler y Gauss los hicieron respetables.', aplicaciones: ['Circuitos de corriente alterna', 'Procesamiento de señales', 'Mecánica cuántica'], ejercicio: 'complex_ops', relacionados: ['aritmetica.15'] }),
  E('raiz', 'símbolo', '√ Raíz cuadrada', { def: 'Número no negativo cuyo cuadrado es el radicando.', intuicion: 'El lado de un cuadrado de área dada.', formula: '\\sqrt{a^2}=|a|', simbolos: [['√', 'raíz cuadrada'], ['|a|', 'valor absoluto']], ejemplos: ['√49 = 7'], historia: 'El símbolo √ se usó desde el siglo XVI (Rudolff, 1525).', aplicaciones: ['Distancias', 'Desviación estándar'], ejercicio: 'roots', relacionados: ['aritmetica.13'] }),
  E('sigma', 'símbolo', 'Σ Sumatoria', { def: 'Notación para una suma de muchos términos.', intuicion: '“Suma todo esto, desde aquí hasta allá”.', formula: '\\sum_{i=1}^{n}a_i=a_1+\\cdots+a_n', simbolos: [['Σ', 'sigma mayúscula'], ['i', 'índice'], ['n', 'último término']], ejemplos: ['Σ_{i=1}^{4} i = 10'], historia: 'Euler la introdujo en 1755.', aplicaciones: ['Estadística', 'Series', 'Integrales (sumas de Riemann)'], ejercicio: 'basic_ops', relacionados: ['estadistica.6'] }),
  E('nabla', 'símbolo', '∇ Nabla', { def: 'Operador que reúne las derivadas parciales: ∇f es el gradiente.', intuicion: 'Apunta hacia donde la función crece más rápido.', formula: '\\nabla f=\\left(\\frac{\\partial f}{\\partial x},\\frac{\\partial f}{\\partial y}\\right)', simbolos: [['∇', 'nabla (del)'], ['∂', 'derivada parcial']], ejemplos: ['f = x² + y² → ∇f = (2x, 2y)'], historia: 'Su nombre viene de una antigua arpa fenicia por su forma.', aplicaciones: ['Optimización', 'Física de campos'], ejercicio: 'gradient', relacionados: ['vectorial.4'] }),
  E('newton-u', 'unidad', 'Newton (N)', { def: 'Unidad de fuerza del SI: la fuerza que da 1 m/s² a una masa de 1 kg.', intuicion: 'Aproximadamente el peso de una manzana pequeña.', formula: '1\\,\\text{N}=1\\,\\text{kg}\\cdot\\text{m/s}^2', simbolos: [['N', 'newton']], ejemplos: ['Una masa de 10 kg pesa ≈ 98 N.'], historia: 'En honor a Isaac Newton.', aplicaciones: ['Mecánica', 'Ingeniería estructural'], ejercicio: 'newton', relacionados: ['fisica.7'] }),
  E('joule', 'unidad', 'Joule (J)', { def: 'Unidad de energía y trabajo: 1 N × 1 m.', intuicion: 'Aproximadamente la energía de levantar una manzana 1 m.', formula: '1\\,\\text{J}=1\\,\\text{N}\\cdot\\text{m}', simbolos: [['J', 'joule']], ejemplos: ['Levantar 1 kg a 1 m: ≈ 9,8 J'], historia: 'En honor a James Prescott Joule.', aplicaciones: ['Energía', 'Calor'], ejercicio: 'work_energy', relacionados: ['fisica.9'] }),
  E('watt', 'unidad', 'Watt (W)', { def: 'Unidad de potencia: 1 joule por segundo.', intuicion: 'Cuánta energía por segundo usa un aparato.', formula: '1\\,\\text{W}=1\\,\\text{J/s}', simbolos: [['W', 'watt']], ejemplos: ['Una bombilla LED de 10 W gasta 10 J cada segundo.'], historia: 'En honor a James Watt.', aplicaciones: ['Electricidad', 'Motores'], ejercicio: 'ohm#2', relacionados: ['fisica2.5'] }),
  E('volt', 'unidad', 'Voltio (V)', { def: 'Unidad de diferencia de potencial eléctrico: 1 joule por coulomb.', intuicion: 'La “presión” eléctrica que empuja la corriente.', formula: '1\\,\\text{V}=1\\,\\text{J/C}', simbolos: [['V', 'voltio']], ejemplos: ['Una pila AA: ≈ 1,5 V.'], historia: 'En honor a Alessandro Volta.', aplicaciones: ['Circuitos'], ejercicio: 'ohm#1', relacionados: ['fisica2.4'] }),
  E('ohm-u', 'unidad', 'Ohmio (Ω)', { def: 'Unidad de resistencia eléctrica: 1 voltio por amperio.', intuicion: 'Qué tanto “estorba” un material al paso de la corriente.', formula: '1\\,\\Omega=1\\,\\text{V/A}', simbolos: [['Ω', 'ohmio']], ejemplos: ['12 V sobre 6 Ω → 2 A.'], historia: 'En honor a Georg Ohm.', aplicaciones: ['Circuitos'], ejercicio: 'ohm#1', relacionados: ['fisica2.4'] }),
  E('radian', 'unidad', 'Radián (rad)', { def: 'Unidad natural de ángulo: el ángulo cuyo arco mide igual que el radio.', intuicion: 'Un giro completo mide 2π radianes ≈ 6,28.', formula: '\\theta=\\frac{s}{r}', simbolos: [['θ', 'ángulo en radianes'], ['s', 'longitud del arco'], ['r', 'radio']], ejemplos: ['180° = π rad.'], historia: 'El término “radián” lo usó James Thomson (1873).', aplicaciones: ['Trigonometría', 'Cálculo', 'Física de ondas'], ejercicio: 'deg_rad', relacionados: ['trigonometria.2'] }),
  E('hertz', 'unidad', 'Hertz (Hz)', { def: 'Unidad de frecuencia: ciclos por segundo.', intuicion: 'Cuántas veces se repite algo cada segundo.', formula: 'f=\\frac1T', simbolos: [['f', 'frecuencia'], ['T', 'periodo']], ejemplos: ['El corazón late a ≈ 1,2 Hz.'], historia: 'En honor a Heinrich Hertz, que generó ondas electromagnéticas en 1887.', aplicaciones: ['Sonido', 'Radio'], ejercicio: 'em_wave', relacionados: ['fisica2.13'] }),
  E('hipotenusa', 'concepto', 'Hipotenusa', { def: 'El lado opuesto al ángulo recto de un triángulo rectángulo; el más largo.', intuicion: 'La “diagonal” del triángulo.', formula: 'c=\\sqrt{a^2+b^2}', simbolos: [['c', 'hipotenusa'], ['a, b', 'catetos']], ejemplos: ['Catetos 3 y 4 → hipotenusa 5.'], historia: 'La palabra viene del griego “hypoteinousa” (que se extiende por debajo).', aplicaciones: ['Distancias', 'Estructuras'], ejercicio: 'pythag', relacionados: ['pitagoras'] }),
  E('capicua', 'curiosidad', 'Capicúa', { def: 'Número (o palabra) que se lee igual de izquierda a derecha y de derecha a izquierda: 12321. El nombre viene del catalán “cap i cua”, cabeza y cola.', intuicion: 'Simetría en el espacio de las cifras: el espejo está en el centro.', formula: '', simbolos: [], ejemplos: ['121, 1331, 2002, 12321'], historia: 'El proceso “invertir y sumar” (algoritmo de Lychrel) genera capicúas a partir de muchos números.', aplicaciones: ['Matemática recreativa', 'Informática (cadenas)'], ejercicio: 'basic_ops', relacionados: [] }),
];

/** Construye la enciclopedia completa a partir del contenido. */
export function buildEncyclopedia() {
  const map = new Map();
  for (const e of EXTRA) map.set(e.id, e);
  for (const l of ALL_LEVELS) {
    const r = REGIONS.find((x) => x.id === l.region);
    map.set(l.id, { id: l.id, type: 'lección', title: l.name.replace(/^JEFE · /, ''), def: l.idea, intuicion: l.why || '', formula: l.formula?.tex || '', simbolos: l.formula?.sym || [], ejemplos: [], historia: '', aplicaciones: [l.app, ...r.applications.slice(0, 2)], ejercicio: l.gens.find((g) => !g.startsWith('project:')), relacionados: l.req.slice(0, 3), region: r.id, regionName: r.name, subject: r.subject, level: l.n });
  }
  for (const t of THEOREMS) map.set(t.id, { id: t.id, type: 'teorema', title: t.name, def: t.problema, intuicion: t.intuicion, formula: t.formula, simbolos: t.simbolos, ejemplos: [t.ejemplo], historia: t.historia, aplicaciones: [t.aplicacion, t.ingenieria], ejercicio: t.guiado, relacionados: [t.level], theorem: true });
  for (const m of MENTORS) map.set(m.id, { id: m.id, type: 'personaje', title: m.name, def: m.bio, intuicion: '', formula: '', simbolos: [], ejemplos: m.facts, historia: m.context, aplicaciones: m.discoveries, ejercicio: m.challenge, relacionados: [], mentor: true, years: m.years, region: m.region, era: m.era });
  return [...map.values()];
}

const norm = (s) => String(s).toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '');
let _enc; let _idx;
export function encyclopedia() { return (_enc ||= buildEncyclopedia()); }

/** Buscador interno: lecciones, fórmulas, personajes, regiones, misiones, laboratorios, historia. */
export function searchAll(query, limit = 30) {
  const q = norm(query).trim();
  if (!q) return [];
  const terms = q.split(/\s+/);
  if (!_idx) {
    _idx = [];
    for (const e of encyclopedia()) _idx.push({ kind: e.type, title: e.title, sub: (e.subject || e.type) + (e.level ? ` · nivel ${e.level}` : ''), text: norm([e.title, e.def, e.formula, e.historia, (e.simbolos || []).flat().join(' '), (e.aplicaciones || []).join(' ')].join(' ')), ref: { type: 'codex', id: e.id } });
    for (const r of REGIONS) _idx.push({ kind: 'región', title: `${r.icon} ${r.name}`, sub: r.subject, text: norm(r.name + ' ' + r.subject + ' ' + r.story), ref: { type: 'region', id: r.id } });
    for (const m of SIDE_MISSIONS) _idx.push({ kind: 'misión', title: `${m.icon} ${m.title}`, sub: m.type, text: norm(m.title + ' ' + m.story), ref: { type: 'mission', id: m.id } });
    for (const lab of ['Mecánica', 'Electricidad', 'Estadística', 'Geometría', 'Álgebra', 'Vectorial', 'Cálculo']) _idx.push({ kind: 'laboratorio', title: `🔬 Laboratorio de ${lab}`, sub: 'Laboratorio', text: norm('laboratorio simulacion ' + lab), ref: { type: 'lab', id: norm(lab) } });
    for (const era of ERAS) { _idx.push({ kind: 'historia', title: `${era.icon} ${era.name}`, sub: era.span, text: norm(era.name + ' ' + era.intro + ' ' + era.events.map((x) => x.title + ' ' + x.text).join(' ')), ref: { type: 'history', id: era.id } }); }
  }
  const scored = [];
  for (const it of _idx) {
    let s = 0; const t = norm(it.title);
    for (const w of terms) { if (t === w) s += 12; else if (t.startsWith(w)) s += 8; else if (t.includes(w)) s += 5; else if (it.text.includes(w)) s += 1; else { s = -1; break; } }
    if (s > 0) scored.push({ ...it, score: s });
  }
  return scored.sort((a, b) => b.score - a.score).slice(0, limit);
}
