// El Universo CAPICÚA: 12 regiones, 16 niveles cada una (15 conceptos + jefe).
// Cada nivel referencia generadores (ver generators.js): "gen#variante@dificultad".

const L = (name, gens, idea, extra = {}) => ({ name, gens: Array.isArray(gens) ? gens : [gens], idea, ...extra });
const F = (tex, ...sym) => ({ tex, sym });

export const REGIONS = [
  {
    id: 'aritmetica', icon: '🏠', name: 'Aldea de los Números', subject: 'Aritmética', color: '#5eead4', music: 'calm',
    landmark: 'village', pos: [0, 0, 0],
    story: 'La aldea donde todo empieza. Aquí los números dejaron de saludarse: el Caos mezcló las cifras y nadie recuerda cómo sumar una fracción. Restaurar la aldea es entender qué significa cada número.',
    applications: ['Dinero y compras', 'Cocina y recetas', 'Descuentos y propinas', 'Medidas y mapas'],
    boss: { name: 'Guardián de los Números', enemy: 'caos', lore: 'Un coloso de cifras cambiantes. Solo cede ante quien comprende fracciones, porcentajes y potencias a la vez.' },
    weapon: 'espada',
    levels: [
      L('Valor posicional', 'place_value', 'Un mismo dígito vale distinto según su posición: en 505 el primer 5 vale cien veces más que el último.', { why: 'Sin valor posicional no existirían los números grandes que usamos cada día.' }),
      L('Operaciones básicas', 'basic_ops', 'Sumar junta, restar compara, multiplicar es sumar repetido y dividir reparte en partes iguales.', { why: 'Todo cálculo, por avanzado que sea, se construye con estas cuatro operaciones.' }),
      L('Números enteros', 'int_ops', 'Los enteros incluyen negativos: sirven para deudas, temperaturas bajo cero y alturas bajo el nivel del mar.', { formula: F('(-)\\cdot(-)=+,\\quad (+)\\cdot(-)=-', ['(-)·(-)', 'dos signos iguales dan positivo'], ['(+)·(-)', 'signos distintos dan negativo']) }),
      L('Divisibilidad', 'divisibility', 'Un número es divisible entre otro si la división es exacta. Hay criterios rápidos para reconocerlo sin dividir.', { req: [2] }),
      L('Números primos', 'prime_factors', 'Los primos son los átomos de los números: todo entero mayor que 1 se escribe de una única forma como producto de primos.', { req: [4] }),
      L('MCD y MCM', 'gcd_lcm', 'El MCD es el mayor divisor común; el MCM, el menor múltiplo común. Ambos salen de los factores primos.', { req: [5], formula: F('\\text{MCD}(a,b)\\cdot\\text{MCM}(a,b) = a\\cdot b', ['MCD', 'máximo común divisor'], ['MCM', 'mínimo común múltiplo']) }),
      L('Fracciones equivalentes', 'frac_simplify', 'Una fracción es una parte de un entero. Fracciones distintas pueden valer lo mismo: 2/4 = 1/2.', { req: [6], formula: F('\\frac{a}{b}=\\frac{a\\cdot k}{b\\cdot k}', ['a', 'numerador: cuántas partes tomas'], ['b', 'denominador: en cuántas partes divides'], ['k', 'cualquier número distinto de 0']) }),
      L('Operaciones con fracciones', 'frac_ops', 'Para sumar fracciones necesitas partes del mismo tamaño (denominador común); para multiplicar, no.', { req: [7], formula: F('\\frac{a}{b}+\\frac{c}{d}=\\frac{ad+bc}{bd}', ['a/b, c/d', 'las fracciones'], ['bd', 'un denominador común (no siempre el menor)']) }),
      L('Decimales', 'decimal_ops', 'Los decimales son fracciones con denominador 10, 100, 1000… La coma separa enteros de partes.', { req: [8] }),
      L('Porcentajes', 'percent', 'Un porcentaje es una fracción “por cada cien”. 25% = 25/100 = 0,25.', { req: [9], formula: F('\\text{parte}=\\frac{p}{100}\\cdot\\text{total}', ['p', 'el porcentaje'], ['total', 'la cantidad completa']) }),
      L('Razones y proporciones', 'ratio_prop', 'Una razón compara dos cantidades; una proporción dice que dos razones son iguales.', { req: [8], formula: F('\\frac{a}{b}=\\frac{c}{d}\\Rightarrow ad=bc', ['ad = bc', 'multiplicación cruzada']) }),
      L('Potencias', 'powers', 'Una potencia es multiplicación repetida. Los exponentes siguen leyes que ahorran trabajo.', { req: [3], formula: F('a^m\\cdot a^n=a^{m+n},\\quad a^0=1,\\quad a^{-n}=\\frac1{a^n}', ['a', 'base'], ['m, n', 'exponentes']) }),
      L('Raíces', 'roots', 'La raíz cuadrada deshace al cuadrado: √25 = 5 porque 5² = 25.', { req: [12], formula: F('\\sqrt{a\\cdot b}=\\sqrt a\\cdot\\sqrt b', ['√', 'raíz cuadrada'], ['a, b', 'números no negativos']) }),
      L('Notación científica', 'sci_not', 'Para números enormes o diminutos se escribe un número entre 1 y 10 multiplicado por una potencia de 10.', { req: [12], formula: F('N=a\\times10^{n},\\ 1\\le a<10', ['a', 'mantisa'], ['n', 'exponente entero']) }),
      L('Racionales, irracionales y complejos', ['classify_number', 'complex_ops'], 'Los racionales son fracciones; los irracionales (√2, π) no lo son; los complejos añaden la unidad imaginaria i con i² = −1.', { req: [13, 14], formula: F('i^2=-1,\\quad (a+bi)+(c+di)=(a+c)+(b+d)i', ['i', 'unidad imaginaria'], ['a', 'parte real'], ['b', 'parte imaginaria']) }),
      L('JEFE · Guardián de los Números', ['frac_ops@3', 'percent@3', 'powers@3', 'gcd_lcm@3', 'roots@2'], 'Combina fracciones, porcentajes, potencias, MCD y raíces para devolver el orden a la aldea.', { boss: true, req: [15, 10, 11] }),
    ],
  },
  {
    id: 'algebra', icon: '🏰', name: 'Castillo del Álgebra', subject: 'Álgebra', color: '#a78bfa', music: 'adventure',
    landmark: 'castle', pos: [14, 1.5, -6],
    story: 'Un castillo de torres cuyas puertas se abren con ecuaciones. El álgebra es el lenguaje que permite hablar de “cualquier número”: cada letra es una caja que guarda un misterio.',
    applications: ['Predecir costos', 'Comparar planes de precios', 'Diseño de juegos', 'Física y programación'],
    prereq: [{ r: 'aritmetica', n: 8 }],
    boss: { name: 'Maestro de las Ecuaciones', enemy: 'desidia', lore: 'Guarda la última puerta. Solo abre para quien despeja, factoriza y resuelve sin miedo a equivocarse.' },
    weapon: 'libro',
    levels: [
      L('Variables', 'var_eval', 'Una variable es una letra que representa un número que puede cambiar. Sustituirla es probar un valor concreto.', { why: 'Las variables permiten escribir reglas generales en lugar de casos sueltos.' }),
      L('Constantes', 'const_vs_var', 'Una constante no cambia; el coeficiente multiplica a la variable. Distinguirlos es leer bien una expresión.', { req: [1] }),
      L('Expresiones', 'var_eval@2', 'Una expresión algebraica combina números, letras y operaciones. Se evalúa respetando el orden de las operaciones.', { req: [2] }),
      L('Términos semejantes', 'like_terms', 'Los términos con la misma parte literal se pueden sumar: 3x + 5x = 8x, pero 3x + 5 no se reduce.', { req: [3] }),
      L('Operaciones algebraicas', 'alg_distribute', 'La propiedad distributiva abre paréntesis: a(b + c) = ab + ac.', { req: [4], formula: F('a(b+c)=ab+ac', ['a', 'factor de afuera'], ['b, c', 'términos del paréntesis']) }),
      L('Monomios', 'monomial_ops', 'Un monomio es un término con coeficiente y variables elevadas a potencias. Se multiplican coeficientes y se suman exponentes.', { req: [3] }),
      L('Polinomios', 'poly_add', 'Un polinomio es una suma de monomios. Se suman y restan agrupando términos del mismo grado.', { req: [6] }),
      L('Productos notables', 'notable_prod', 'Algunos productos aparecen tanto que conviene memorizar su patrón… entendiendo de dónde salen.', { req: [5, 7], formula: F('(a+b)^2=a^2+2ab+b^2,\\quad (a+b)(a-b)=a^2-b^2', ['a, b', 'cualquier término'], ['2ab', 'doble producto: el que se olvida']) }),
      L('Factorización', 'factor', 'Factorizar es escribir un polinomio como producto: lo contrario de desarrollar.', { req: [8], formula: F('x^2+(a+b)x+ab=(x+a)(x+b)', ['a, b', 'dos números que suman el coeficiente de x y multiplican al término independiente']) }),
      L('Ecuaciones', 'linear_eq', 'Una ecuación es una balanza: lo que haces de un lado debes hacerlo del otro. Resolver es dejar la incógnita sola.', { req: [4], formula: F('ax+b=c\\ \\Rightarrow\\ x=\\frac{c-b}{a}', ['x', 'incógnita'], ['a, b, c', 'números conocidos, con a ≠ 0']) }),
      L('Despeje', 'solve_for', 'Despejar una letra en una fórmula es resolver una ecuación donde la “solución” es una expresión.', { req: [10] }),
      L('Sistemas', 'system_2x2', 'Un sistema reúne varias ecuaciones que deben cumplirse a la vez. Geométricamente: dónde se cruzan dos rectas.', { req: [11] }),
      L('Funciones', 'func_eval', 'Una función asigna a cada entrada exactamente una salida: f(x) es “lo que x produce”.', { req: [9, 12], formula: F('f(x)=ax^2+bx+c', ['x', 'entrada'], ['f(x)', 'salida'], ['a, b, c', 'parámetros']) }),
      L('Gráficas', 'line_graph', 'La gráfica dibuja todos los pares (x, f(x)). La pendiente dice qué tan rápido cambia una recta.', { req: [13], formula: F('y=mx+b,\\quad m=\\frac{y_2-y_1}{x_2-x_1}', ['m', 'pendiente'], ['b', 'ordenada al origen (corte con el eje y)']) }),
      L('Desafíos', ['quadratic_eq', 'inequality', 'spot_error'], 'Ecuaciones cuadráticas, desigualdades y caza de errores: el entrenamiento antes del jefe.', { req: [14], formula: F('x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}', ['a, b, c', 'coeficientes de ax²+bx+c'], ['b²−4ac', 'discriminante: cuántas soluciones reales hay']) }),
      L('JEFE · Maestro de las Ecuaciones', ['linear_eq@3', 'system_2x2@2', 'quadratic_eq@3', 'factor@3'], 'Ecuaciones, sistemas, cuadráticas y factorización combinadas.', { boss: true, req: [15] }),
    ],
  },
  {
    id: 'geometria', icon: '📐', name: 'Templo de la Geometría', subject: 'Geometría', color: '#fbbf24', music: 'mystery',
    landmark: 'temple', pos: [24, -1, 8],
    story: 'Un templo con columnas imposibles. Cada sala guarda una forma y su secreto: la geometría nació de medir la tierra, y aún hoy mide el mundo.',
    applications: ['Arquitectura', 'Diseño gráfico', 'Construcción', 'Videojuegos 3D'],
    prereq: [{ r: 'aritmetica', n: 8 }],
    boss: { name: 'Titán de las Formas', enemy: 'confusion', lore: 'Un gigante hecho de polígonos que cambian. Solo lo detiene quien ve las relaciones entre figuras.' },
    weapon: 'escudo',
    levels: [
      L('Puntos y plano', 'geo_distance', 'Un punto marca una posición; con dos coordenadas ubicamos cualquier punto del plano y medimos distancias.', { formula: F('d=\\sqrt{(x_2-x_1)^2+(y_2-y_1)^2}', ['d', 'distancia'], ['(x₁,y₁), (x₂,y₂)', 'los dos puntos']) }),
      L('Rectas y segmentos', 'midpoint', 'Una recta no tiene fin; un segmento sí. Su punto medio es el promedio de los extremos.', { req: [1], formula: F('M=\\left(\\tfrac{x_1+x_2}{2},\\tfrac{y_1+y_2}{2}\\right)', ['M', 'punto medio']) }),
      L('Ángulos', 'angles', 'Un ángulo mide cuánto se abre un giro. Complementarios suman 90°, suplementarios 180°.', { req: [2] }),
      L('Triángulos', 'triangle_angle', 'Los ángulos interiores de cualquier triángulo suman 180°. El triángulo es la figura más rígida y fundamental.', { req: [3], formula: F('\\alpha+\\beta+\\gamma=180^\\circ') }),
      L('Teorema de Pitágoras', 'pythag', 'En un triángulo rectángulo, el cuadrado de la hipotenusa es la suma de los cuadrados de los catetos.', { req: [4], formula: F('a^2+b^2=c^2', ['a, b', 'catetos (forman el ángulo recto)'], ['c', 'hipotenusa (el lado opuesto al ángulo recto)']), mission: 'puente-pitagoras' }),
      L('Cuadriláteros', 'quad_area#1', 'Cuadrados, rectángulos, rombos y trapecios: cada uno con su regla de área.', { req: [4] }),
      L('Polígonos', 'polygon_angles', 'Todo polígono se corta en triángulos; de ahí salen sus ángulos y diagonales.', { req: [6], formula: F('S=(n-2)\\cdot180^\\circ', ['n', 'número de lados'], ['S', 'suma de ángulos interiores']) }),
      L('Circunferencia', 'circle#1', 'En cualquier circunferencia, la razón entre su longitud y su diámetro es el mismo número: π.', { req: [5], formula: F('C=2\\pi r', ['C', 'circunferencia'], ['r', 'radio']) }),
      L('Círculos', 'circle#2', 'El área del círculo crece con el cuadrado del radio.', { req: [8], formula: F('A=\\pi r^2', ['A', 'área'], ['r', 'radio']) }),
      L('Áreas y perímetros', 'quad_area#3', 'El perímetro mide el borde; el área, la superficie. Son cosas distintas.', { req: [7, 9] }),
      L('Volúmenes', 'volume', 'El volumen mide el espacio que ocupa un cuerpo: base por altura, y un ajuste para conos y esferas.', { req: [10], formula: F('V_{cil}=\\pi r^2h,\\quad V_{esf}=\\tfrac43\\pi r^3', ['r', 'radio'], ['h', 'altura']) }),
      L('Semejanza', 'similar', 'Figuras semejantes tienen la misma forma. Longitudes ×k, áreas ×k², volúmenes ×k³.', { req: [5] }),
      L('Congruencia', ['congruence', 'concept:congruence_ctx'], 'Dos figuras son congruentes si se pueden superponer exactamente. Hay criterios para saberlo con pocos datos.', { req: [12] }),
      L('Transformaciones', 'transform', 'Trasladar, reflejar, rotar y escalar: mover figuras sin (o casi sin) deformarlas.', { req: [13] }),
      L('Geometría analítica', ['line_graph@2', 'geo_distance@2'], 'Cuando las figuras se vuelven ecuaciones, la geometría y el álgebra se dan la mano (Descartes).', { req: [14, 2] }),
      L('JEFE · Titán de las Formas', ['pythag@3', 'quad_area@3', 'circle@3', 'volume@3', 'polygon_angles@3'], 'Combina áreas, volúmenes y ángulos para vencer al Titán.', { boss: true, req: [15, 11] }),
    ],
  },
  {
    id: 'trigonometria', icon: '🔺', name: 'Montañas Trigonométricas', subject: 'Trigonometría', color: '#fb923c', music: 'explore',
    landmark: 'mountains', pos: [30, 3, -14],
    story: 'Cumbres que se miden sin escalarlas. La trigonometría convierte ángulos en distancias: así se midieron estrellas, mares y montañas.',
    applications: ['Topografía y navegación', 'Sonido y música', 'Gráficos 3D', 'Astronomía'],
    prereq: [{ r: 'geometria', n: 5 }],
    boss: { name: 'Señor de los Ángulos', enemy: 'duda', lore: 'Domina las ondas de la montaña. Solo lo vence quien ve el círculo unitario como una brújula.' },
    weapon: 'arco',
    levels: [
      L('Ángulos y grados', 'angle_class', 'Un giro completo mide 360°. Clasificamos ángulos como agudo, recto, obtuso, llano…'),
      L('Radianes', 'deg_rad', 'El radián mide el ángulo por la longitud del arco que abarca; un giro completo son 2π radianes.', { req: [1], formula: F('180^\\circ=\\pi\\ \\text{rad}', ['rad', 'radianes']) }),
      L('Razones trigonométricas', 'trig_ratio', 'En un triángulo rectángulo, las razones entre lados dependen solo del ángulo: seno, coseno y tangente.', { req: [1], formula: F('\\sin\\theta=\\tfrac{\\text{op}}{\\text{hip}},\\ \\cos\\theta=\\tfrac{\\text{ady}}{\\text{hip}},\\ \\tan\\theta=\\tfrac{\\text{op}}{\\text{ady}}', ['op', 'cateto opuesto a θ'], ['ady', 'cateto adyacente a θ'], ['hip', 'hipotenusa']) }),
      L('Resolver triángulos rectángulos', 'right_solve', 'Con un ángulo y un lado se hallan los demás lados usando las razones.', { req: [3] }),
      L('Ángulos notables', 'special_angles', '30°, 45° y 60° salen de triángulos especiales y dan valores exactos con raíces.', { req: [3] }),
      L('Círculo unitario', 'unit_circle', 'En una circunferencia de radio 1, el punto en el ángulo θ tiene coordenadas (cos θ, sen θ).', { req: [2, 5], formula: F('P(\\theta)=(\\cos\\theta,\\ \\sin\\theta)') }),
      L('Cuadrantes y signos', 'quadrant_signs', 'Según el cuadrante, seno, coseno y tangente son positivos o negativos.', { req: [6] }),
      L('Identidades', 'identity', 'Relaciones que valen siempre; la primera es Pitágoras en el círculo unitario.', { req: [7], formula: F('\\sin^2\\theta+\\cos^2\\theta=1') }),
      L('Ley de senos', 'law_sines', 'En cualquier triángulo, cada lado es proporcional al seno de su ángulo opuesto.', { req: [4], formula: F('\\frac{a}{\\sin A}=\\frac{b}{\\sin B}=\\frac{c}{\\sin C}') }),
      L('Ley de cosenos', 'law_cosines', 'Generaliza Pitágoras a triángulos no rectángulos.', { req: [9], formula: F('c^2=a^2+b^2-2ab\\cos C', ['C', 'ángulo entre los lados a y b']) }),
      L('Funciones trigonométricas', 'trig_graph#amp', 'Seno y coseno describen oscilaciones: la amplitud es la altura de la onda.', { req: [8], formula: F('y=A\\sin(Bx)', ['A', 'amplitud'], ['B', 'frecuencia angular']) }),
      L('Periodo y gráficas', 'trig_graph#per', 'El periodo es lo que tarda una onda en repetirse: T = 2π/B.', { req: [11], formula: F('T=\\frac{2\\pi}{|B|}') }),
      L('Ecuaciones trigonométricas', 'trig_eq', 'Resolver sen x = ½ es buscar todos los ángulos con esa altura en el círculo.', { req: [12] }),
      L('Aplicaciones', 'elevation', 'Ángulos de elevación y depresión permiten medir alturas y distancias inaccesibles.', { req: [4] }),
      L('Ondas y señales', ['trig_graph', 'deg_rad@3'], 'Sonido, luz y señales eléctricas son sumas de ondas sinusoidales.', { req: [12, 14] }),
      L('JEFE · Señor de los Ángulos', ['special_angles@3', 'unit_circle@3', 'law_cosines', 'law_sines', 'identity@3'], 'Domina el círculo, las leyes y las identidades.', { boss: true, req: [13, 15, 10] }),
    ],
  },
  {
    id: 'estadistica', icon: '📊', name: 'Ciudad de los Datos', subject: 'Estadística y Probabilidad', color: '#38bdf8', music: 'calm',
    landmark: 'city', pos: [-12, 2, 14],
    story: 'Una ciudad de torres hechas de gráficas. Aquí se aprende a leer el mundo con datos y a razonar con incertidumbre.',
    applications: ['Ciencia de datos', 'Medicina', 'Deportes', 'Finanzas e IA'],
    prereq: [{ r: 'aritmetica', n: 10 }],
    boss: { name: 'Oráculo de los Datos', enemy: 'duda', lore: 'Predice… pero solo con datos honestos. Se vence razonando con cuidado, no adivinando.' },
    weapon: 'baculo',
    levels: [
      L('Datos y tablas', 'freq_table', 'Los datos se organizan en tablas de frecuencia para ver qué pasa de verdad.'),
      L('Gráficas', ['chart_read', 'concept:data_viz'], 'Una buena gráfica deja ver el patrón; una mala lo esconde (o engaña).', { req: [1] }),
      L('Media', 'stat_central#media', 'La media es el “reparto equitativo”: suma de datos entre cantidad de datos.', { req: [1], formula: F('\\bar x=\\frac{x_1+\\cdots+x_n}{n}', ['x̄', 'media'], ['n', 'cantidad de datos']) }),
      L('Mediana', 'stat_central#mediana', 'La mediana es el dato central cuando se ordenan; no se deja engañar por valores extremos.', { req: [3] }),
      L('Moda y rango', ['stat_central#moda', 'stat_central#rango'], 'La moda es lo más frecuente; el rango, la distancia entre máximo y mínimo.', { req: [3] }),
      L('Varianza', 'variance', 'Mide qué tanto se alejan los datos de la media, promediando los cuadrados de las desviaciones.', { req: [3], formula: F('\\sigma^2=\\frac{1}{n}\\sum (x_i-\\mu)^2', ['μ', 'media'], ['σ²', 'varianza']) }),
      L('Desviación estándar', 'variance@3', 'Es la raíz de la varianza: en las mismas unidades que los datos.', { req: [6], formula: F('\\sigma=\\sqrt{\\sigma^2}') }),
      L('Probabilidad básica', 'probability@1', 'La probabilidad mide la incertidumbre entre 0 (imposible) y 1 (seguro).', { req: [1], formula: F('P(A)=\\frac{\\text{casos favorables}}{\\text{casos posibles}}') }),
      L('Probabilidad compuesta', 'probability@3', 'Eventos independientes se multiplican; sin reposición, la probabilidad cambia (condicional).', { req: [8], formula: F('P(A\\cap B)=P(A)\\,P(B|A)') }),
      L('Combinatoria', 'combinatorics', 'Contar sin listar: permutaciones (orden importa) y combinaciones (no importa).', { req: [8], formula: F('\\binom nk=\\frac{n!}{k!(n-k)!}') }),
      L('Distribución binomial', 'binomial', 'Cuenta éxitos en intentos repetidos con la misma probabilidad.', { req: [9, 10], formula: F('P(X=k)=\\binom nk p^k(1-p)^{n-k}') }),
      L('Distribución normal y z', 'zscore', 'Muchos fenómenos forman una campana. El puntaje z dice a cuántas desviaciones está un dato.', { req: [7], formula: F('z=\\frac{x-\\mu}{\\sigma}') }),
      L('Muestreo', 'concept:inference', 'Estudiar una muestra para saber de una población: ¿qué tan confiable es?', { req: [12] }),
      L('Inferencia básica', ['conf_int', 'concept:inference'], 'Un intervalo de confianza acompaña la estimación con su margen de error.', { req: [13], formula: F('ME=z\\cdot\\frac{\\sigma}{\\sqrt n}') }),
      L('Proyecto de datos', 'project:data', 'Analiza mediciones reales: media, dispersión y valores atípicos.', { req: [7, 14] }),
      L('JEFE · Oráculo de los Datos', ['variance@3', 'probability@3', 'combinatorics@3', 'binomial', 'zscore'], 'Datos, probabilidad y azar en una sola misión.', { boss: true, req: [15, 11] }),
    ],
  },
  {
    id: 'algebralineal', icon: '🤖', name: 'Laboratorio Matricial', subject: 'Álgebra Lineal', color: '#34d399', music: 'tech',
    landmark: 'lab', pos: [-22, -2, 2],
    story: 'Robots que se transforman con una sola matriz. El álgebra lineal es el idioma de los gráficos, la IA y la ingeniería moderna.',
    applications: ['Gráficos 3D y videojuegos', 'Inteligencia artificial', 'Robótica', 'Compresión de imágenes'],
    prereq: [{ r: 'algebra', n: 12 }],
    boss: { name: 'Constructor de Matrices', enemy: 'bloqueo', lore: 'Un robot hecho de filas y columnas. Se desarma si entiendes qué hace cada matriz.' },
    weapon: 'lanza',
    levels: [
      L('Vectores', 'vec_ops', 'Un vector tiene magnitud y dirección. Se suman componente a componente y se escalan multiplicando.', { formula: F('\\vec a+\\vec b=(a_1+b_1,\\ a_2+b_2)') }),
      L('Producto punto', 'dot_prod', 'El producto punto resume qué tanto apuntan dos vectores en la misma dirección.', { req: [1], formula: F('\\vec a\\cdot\\vec b=\\sum a_ib_i=|a||b|\\cos\\theta') }),
      L('Matrices', 'mat_ops@1', 'Una matriz es una tabla de números; puede representar datos o una transformación.', { req: [1] }),
      L('Operaciones matriciales', 'mat_ops@2', 'Sumar es entrada a entrada; multiplicar es fila por columna y NO conmuta.', { req: [3] }),
      L('Determinantes 2×2', 'det2@1', 'El determinante dice cuánto escala el área una transformación (y si se invierte).', { req: [3], formula: F('\\det\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}=ad-bc') }),
      L('Determinantes 3×3', 'det2@3', 'En 3×3 se expande por cofactores; el determinante es el factor de volumen.', { req: [5] }),
      L('Inversa', 'inv2', 'La inversa deshace una transformación. Existe solo si el determinante no es 0.', { req: [5], formula: F('A^{-1}=\\frac{1}{\\det A}\\begin{pmatrix}d&-b\\\\-c&a\\end{pmatrix}') }),
      L('Sistemas lineales', 'system_3x3', 'Eliminación gaussiana: convierte el sistema en uno triangular fácil de resolver.', { req: [7] }),
      L('Espacios vectoriales', 'concept:vector_space', 'Un espacio vectorial es cualquier conjunto cerrado bajo suma y escalares: flechas, polinomios, funciones…', { req: [2] }),
      L('Independencia lineal', 'lin_indep', 'Vectores independientes no se pueden obtener unos de otros: aportan información nueva.', { req: [9, 5] }),
      L('Transformaciones lineales', 'mat_vec', 'Girar, escalar o reflejar es multiplicar por una matriz.', { req: [4] }),
      L('Valores propios', 'eig2', 'Direcciones que la transformación solo estira. El factor de estiramiento es el valor propio.', { req: [10, 11], formula: F('A\\vec v=\\lambda\\vec v', ['v', 'vector propio'], ['λ', 'valor propio']) }),
      L('Vectores propios', 'eigvec', 'Los ejes naturales de una transformación: sobre ellos solo estira o encoge.', { req: [12] }),
      L('Diagonalización', ['eig2@3', 'eigvec'], 'En la base de vectores propios, la matriz se vuelve diagonal y todo se simplifica.', { req: [13] }),
      L('Aplicación: transformar imágenes', 'mat_vec', 'Cada píxel es un vector; una matriz lo mueve. Así funcionan rotar y escalar imágenes.', { req: [11], lab: 'matrix' }),
      L('JEFE · Constructor de Matrices', ['mat_ops@3', 'inv2', 'det2@3', 'system_3x3', 'eig2@3'], 'Construye, invierte y diagonaliza.', { boss: true, req: [14, 15, 8] }),
    ],
  },
  {
    id: 'calculo', icon: '🌌', name: 'Universo del Cálculo', subject: 'Cálculo Diferencial e Integral', color: '#818cf8', music: 'space',
    landmark: 'cosmos', pos: [8, 6, -26],
    story: 'Galaxias que cambian a cada instante. El cálculo estudia el cambio y la acumulación: de ahí salió la física moderna.',
    applications: ['Velocidad y aceleración', 'Optimización de recursos', 'Economía', 'Aprendizaje automático'],
    prereq: [{ r: 'algebra', n: 14 }, { r: 'trigonometria', n: 8 }],
    boss: { name: 'Guardián del Infinito', enemy: 'miedo', lore: 'Se alimenta del miedo a lo infinito. Se rinde ante quien entiende límites y series.' },
    weapon: 'martillo',
    levels: [
      L('Funciones', ['func_eval@2', 'concept:domain_range'], 'El cálculo trabaja con funciones: dominio (entradas válidas) y rango (salidas).'),
      L('Límites intuitivos', 'limit_poly', 'El límite pregunta a qué valor se acerca f(x) cuando x se acerca a un punto, sin necesariamente llegar.', { req: [1], formula: F('\\lim_{x\\to a}f(x)=L') }),
      L('Límites algebraicos', 'limit_factor', 'Las indeterminaciones 0/0 se resuelven factorizando y simplificando.', { req: [2] }),
      L('Límites al infinito', 'limit_inf', 'Qué hace una función cuando x crece sin límite: manda el término de mayor grado.', { req: [2] }),
      L('Continuidad', ['continuity', 'concept:continuity'], 'Una función continua no tiene saltos ni agujeros: lím f(x) = f(a).', { req: [3] }),
      L('La derivada', 'tangent_slope', 'La derivada es la pendiente de la tangente: la razón de cambio instantánea.', { req: [5, 3], formula: F("f'(a)=\\lim_{h\\to0}\\frac{f(a+h)-f(a)}{h}") }),
      L('Reglas de derivación', 'deriv_poly', 'Reglas para derivar sin calcular el límite cada vez.', { req: [6], formula: F("\\frac{d}{dx}x^n=nx^{n-1}") }),
      L('Producto y cociente', 'deriv_rules#producto', 'Cómo derivar productos y cocientes de funciones.', { req: [7], formula: F("(uv)'=u'v+uv'") }),
      L('Regla de la cadena', 'deriv_rules#cadena', 'Derivar funciones compuestas: derivada de afuera por derivada de adentro.', { req: [8], formula: F("\\frac{d}{dx}f(g(x))=f'(g(x))\\,g'(x)") }),
      L('Aplicaciones de la derivada', 'optimize', 'Máximos, mínimos y optimización: dónde la derivada se anula.', { req: [9] }),
      L('La integral', 'integral_poly', 'La integral deshace la derivada y acumula cantidades.', { req: [7], formula: F('\\int x^n\\,dx=\\frac{x^{n+1}}{n+1}+C') }),
      L('Teorema fundamental', 'definite_integral', 'Derivar e integrar son procesos inversos: ∫ₐᵇ f = F(b) − F(a).', { req: [11, 10], formula: F('\\int_a^bf(x)\\,dx=F(b)-F(a)') }),
      L('Técnicas de integración', 'integral_tricks', 'Sustitución y partes: la regla de la cadena y del producto al revés.', { req: [12] }),
      L('Áreas y volúmenes', 'definite_integral@3', 'La integral definida da el área bajo una curva y, girándola, volúmenes de revolución.', { req: [12] }),
      L('Series', ['series_geom', 'concept:infinity'], 'Sumar infinitos términos puede dar un número finito.', { req: [4, 13], formula: F('\\sum_{n=0}^{\\infty}ar^n=\\frac{a}{1-r},\\ |r|<1') }),
      L('JEFE · Guardián del Infinito', ['deriv_rules@3', 'integral_tricks', 'limit_factor', 'optimize', 'series_geom'], 'Límites, derivadas, integrales y series.', { boss: true, req: [15, 10, 14] }),
    ],
  },
  {
    id: 'vectorial', icon: '🌀', name: 'Dimensión Vectorial', subject: 'Cálculo Vectorial', color: '#f472b6', music: 'space',
    landmark: 'vortex', pos: [-4, 7, -40],
    story: 'Un remolino de campos y flechas. Cada punto del espacio guarda un vector: así se describen el viento, la gravedad y el magnetismo.',
    applications: ['Fluidos', 'Electromagnetismo', 'Meteorología', 'Gráficos por computadora'],
    prereq: [{ r: 'calculo', n: 10 }, { r: 'algebralineal', n: 2 }],
    boss: { name: 'Señor de los Campos', enemy: 'confusion', lore: 'Controla corrientes invisibles. Su punto débil: la divergencia y el rotacional.' },
    weapon: 'lanza',
    levels: [
      L('Vectores en R³', 'vec3_ops', 'Los vectores del espacio tienen tres componentes; el producto cruz da un vector perpendicular.', { formula: F('\\vec a\\times\\vec b=(a_2b_3-a_3b_2,\\ a_3b_1-a_1b_3,\\ a_1b_2-a_2b_1)') }),
      L('Funciones de varias variables', 'partial@1', 'f(x, y) asigna un valor a cada punto del plano: un relieve.', { req: [1] }),
      L('Derivadas parciales', 'partial@2', 'Derivar respecto a una variable manteniendo constantes las demás.', { req: [2], formula: F('\\frac{\\partial f}{\\partial x}') }),
      L('Gradiente', 'gradient', 'El gradiente apunta hacia donde la función crece más rápido.', { req: [3], formula: F('\\nabla f=\\left(\\frac{\\partial f}{\\partial x},\\frac{\\partial f}{\\partial y}\\right)') }),
      L('Derivada direccional', 'dir_deriv', 'Rapidez de cambio en cualquier dirección: el gradiente por un vector unitario.', { req: [4], formula: F('D_{\\vec u}f=\\nabla f\\cdot\\vec u') }),
      L('Campos vectoriales', 'divergence@1', 'Un campo asigna un vector a cada punto: la velocidad del viento, por ejemplo.', { req: [3] }),
      L('Divergencia', 'divergence', 'Mide si un campo “nace” (fuente) o “desaparece” (sumidero) en un punto.', { req: [6], formula: F('\\nabla\\cdot\\vec F=\\frac{\\partial P}{\\partial x}+\\frac{\\partial Q}{\\partial y}+\\frac{\\partial R}{\\partial z}') }),
      L('Rotacional', 'curl2d', 'Mide cuánto “gira” un campo alrededor de un punto.', { req: [6], formula: F('(\\nabla\\times\\vec F)_z=\\frac{\\partial Q}{\\partial x}-\\frac{\\partial P}{\\partial y}') }),
      L('Integrales dobles', 'double_integral', 'Integrar sobre una región plana: volúmenes bajo superficies.', { req: [3] }),
      L('Integrales múltiples', 'double_integral@2', 'Integrales triples y cambios de coordenadas para masas y centros.', { req: [9] }),
      L('Integrales de línea', 'line_work', 'Sumar un campo a lo largo de una curva: trabajo de una fuerza.', { req: [6], formula: F('W=\\int_C\\vec F\\cdot d\\vec r') }),
      L('Campos conservativos', 'gradient@2', 'Si el rotacional es 0, el trabajo no depende del camino: hay un potencial.', { req: [8, 11] }),
      L('Integrales de superficie', 'flux', 'El flujo mide cuánto campo atraviesa una superficie.', { req: [11], formula: F('\\Phi=\\iint_S\\vec F\\cdot\\hat n\\,dS') }),
      L('Teoremas de Green, Stokes y Gauss', 'divergence@2', 'Relacionan integrales sobre una región con integrales en su frontera.', { req: [12, 7] }),
      L('Aplicación: campos físicos', 'line_work@3', 'Trabajo, flujo y potencial en situaciones reales.', { req: [13] }),
      L('JEFE · Señor de los Campos', ['gradient', 'divergence', 'curl2d', 'double_integral', 'flux'], 'Gradiente, divergencia, rotacional e integrales.', { boss: true, req: [14, 15, 10] }),
    ],
  },
  {
    id: 'edo', icon: '⚙️', name: 'Fábrica de Ecuaciones', subject: 'Ecuaciones Diferenciales', color: '#fb7185', music: 'tech',
    landmark: 'factory', pos: [-26, -3, -20],
    story: 'Engranajes que describen el cambio. Una ecuación diferencial es una regla sobre cómo evoluciona algo: poblaciones, circuitos, resortes.',
    applications: ['Modelado de poblaciones', 'Circuitos eléctricos', 'Vibraciones y estructuras', 'Control automático'],
    prereq: [{ r: 'calculo', n: 12 }],
    boss: { name: 'Arquitecto Dinámico', enemy: 'frustracion', lore: 'Construye mundos que cambian. Su punto débil: entender qué dice cada ecuación.' },
    weapon: 'martillo',
    levels: [
      L('¿Qué es una EDO?', 'ode_verify', 'Una ecuación diferencial relaciona una función con sus derivadas. Su solución es una función, no un número.'),
      L('Integración directa', 'ode_direct', 'Cuando y′ solo depende de x, se integra; la condición inicial fija la constante.', { req: [1] }),
      L('Variables separables', 'ode_sep', 'Se separan las variables a cada lado e integran: y′ = ky da crecimiento exponencial.', { req: [2], formula: F("y'=ky\\ \\Rightarrow\\ y=Ce^{kt}") }),
      L('Crecimiento y decaimiento', 'ode_model#dup', 'Poblaciones y desintegración radiactiva siguen la misma ecuación.', { req: [3] }),
      L('Ley de enfriamiento', 'ode_model#cool', 'Los cuerpos tienden al equilibrio con el ambiente de forma exponencial.', { req: [3] }),
      L('Lineales de primer orden', 'ode_direct@2', 'Ecuaciones y′ + p(x)y = q(x): se resuelven con un factor integrante.', { req: [4] }),
      L('Modelado', 'ode_model', 'Traducir una situación real a una ecuación diferencial y analizarla.', { req: [4, 5] }),
      L('Velocidad terminal', 'terminal', 'Cuando la fuerza de arrastre iguala al peso, la velocidad deja de crecer.', { req: [7] }),
      L('Segundo orden', 'ode2_char', 'Ecuaciones con y″: se prueba y = e^{rx} y sale la ecuación característica.', { req: [6], formula: F("ay''+by'+cy=0\\ \\Rightarrow\\ ar^2+br+c=0") }),
      L('Raíces reales y complejas', 'ode2_char@2', 'Las raíces de la característica dicen si la solución crece, decae u oscila.', { req: [9] }),
      L('Oscilaciones', 'oscillation', 'Resortes y péndulos: el movimiento armónico simple.', { req: [10], formula: F('\\omega=\\sqrt{k/m},\\quad T=\\frac{2\\pi}{\\omega}') }),
      L('Amortiguamiento y resonancia', 'oscillation@2', 'Con fricción las oscilaciones se apagan; con fuerza periódica puede haber resonancia.', { req: [11] }),
      L('Sistemas de EDO', 'eig2', 'Varias magnitudes que se influyen: se resuelven con valores propios.', { req: [10] }),
      L('Estabilidad', 'eig2@3', 'El signo de los valores propios dice si un sistema se estabiliza o explota.', { req: [13] }),
      L('Aplicaciones físicas', ['terminal', 'oscillation'], 'Paracaidistas, suspensiones, circuitos RLC.', { req: [8, 12] }),
      L('JEFE · Arquitecto Dinámico', ['ode_sep', 'ode2_char@2', 'oscillation@2', 'ode_model', 'terminal'], 'Modelar, resolver e interpretar.', { boss: true, req: [14, 15] }),
    ],
  },
  {
    id: 'fisica', icon: '🔬', name: 'Laboratorio de Mecánica', subject: 'Física General', color: '#f59e0b', music: 'tech',
    landmark: 'mech', pos: [20, -2, 26],
    story: 'Poleas, rampas y proyectiles. La mecánica describe por qué se mueve lo que se mueve… y casi todo lo demás en la física se apoya en ella.',
    applications: ['Ingeniería civil y mecánica', 'Deportes', 'Seguridad vial', 'Aeronáutica'],
    prereq: [{ r: 'algebra', n: 10 }, { r: 'trigonometria', n: 4 }],
    boss: { name: 'Arquitecto de las Fuerzas', enemy: 'desidia', lore: 'Un coloso de poleas. Cada fuerza tiene su respuesta: dibújalas todas.' },
    weapon: 'escudo',
    levels: [
      L('Unidades y mediciones', 'unit_conv', 'Toda magnitud tiene unidades; convertirlas y comprobarlas evita errores catastróficos.'),
      L('Vectores en física', 'vec_comp', 'Fuerzas y velocidades son vectores: se descomponen en componentes.', { req: [1], formula: F('F_x=F\\cos\\theta,\\quad F_y=F\\sin\\theta') }),
      L('Cinemática en 1D', 'kinematics#1', 'Describir el movimiento: posición, velocidad y aceleración.', { req: [1], formula: F('v=v_0+at', ['v₀', 'velocidad inicial'], ['a', 'aceleración'], ['t', 'tiempo']) }),
      L('Cinemática avanzada', 'kinematics#2', 'Movimiento uniformemente acelerado: distancia, velocidad y tiempo.', { req: [3], formula: F('x=v_0t+\\tfrac12at^2,\\quad v^2=v_0^2+2a\\Delta x') }),
      L('Caída libre', 'free_fall', 'Sin aire, todos los cuerpos caen con la misma aceleración g ≈ 9,8 m/s².', { req: [4], formula: F('h=\\tfrac12gt^2') }),
      L('Proyectiles', 'projectile', 'Un proyectil combina movimiento horizontal uniforme y vertical acelerado.', { req: [2, 5], lab: 'projectile', formula: F('R=\\frac{v_0^2\\sin2\\theta}{g}') }),
      L('Leyes de Newton', 'newton', 'La fuerza neta produce aceleración: F = ma. Sin fuerza neta, no hay cambio de movimiento.', { req: [2, 3], lab: 'newton', formula: F('\\sum\\vec F=m\\vec a', ['F', 'fuerza neta (N)'], ['m', 'masa (kg)'], ['a', 'aceleración (m/s²)']) }),
      L('Fricción e inclinados', 'incline', 'El peso se descompone en componente paralela y perpendicular al plano.', { req: [7], formula: F('a=g\\sin\\theta') }),
      L('Trabajo y energía', 'work_energy', 'El trabajo transfiere energía; la energía cinética depende del cuadrado de la velocidad.', { req: [7], formula: F('W=Fd\\cos\\theta,\\ K=\\tfrac12mv^2') }),
      L('Conservación de energía', 'work_energy@3', 'La energía no se crea ni se destruye: cambia de forma.', { req: [9] }),
      L('Cantidad de movimiento', 'momentum', 'El momento total se conserva en choques y explosiones.', { req: [7], formula: F('p=mv,\\quad m_1v_1+m_2v_2=\\text{cte}') }),
      L('Rotación', ['rotation', 'centripetal'], 'Torque, movimiento circular y aceleración centrípeta.', { req: [2, 7] }),
      L('Fluidos', 'fluids_heat_waves#1', 'La presión crece con la profundidad: la base de submarinos y presas.', { req: [9], formula: F('P=\\rho gh') }),
      L('Termodinámica', 'fluids_heat_waves#2', 'Calor y temperatura: cuánta energía hace falta para calentar algo.', { req: [9], formula: F('Q=mc\\Delta T') }),
      L('Ondas', 'fluids_heat_waves#3', 'Las ondas transportan energía sin transportar materia.', { req: [11], formula: F('v=f\\lambda') }),
      L('JEFE · Arquitecto de las Fuerzas', ['newton@3', 'projectile', 'work_energy@3', 'momentum@2', 'incline'], 'Fuerzas, energía y movimiento.', { boss: true, req: [14, 15, 12] }),
    ],
  },
  {
    id: 'fisica2', icon: '⚡', name: 'Central Electromagnética', subject: 'Electromagnetismo y Ondas', color: '#22d3ee', music: 'tech',
    landmark: 'power', pos: [-16, 3, 34],
    story: 'Una central donde fluyen cargas y campos. La electricidad y el magnetismo son dos caras de lo mismo: de ahí viene toda la tecnología moderna.',
    applications: ['Electrónica', 'Energía y redes eléctricas', 'Telecomunicaciones', 'Medicina (resonancia)'],
    prereq: [{ r: 'fisica', n: 9 }],
    boss: { name: 'Señor de la Energía', enemy: 'procrastinacion', lore: 'Controla la corriente. Se detiene solo si sabes cómo se conectan los circuitos.' },
    weapon: 'orbe',
    levels: [
      L('Carga eléctrica', 'coulomb', 'Hay cargas positivas y negativas; las iguales se repelen y las distintas se atraen.', { formula: F('F=k\\frac{q_1q_2}{r^2}', ['k', '8,99×10⁹ N·m²/C²'], ['q', 'cargas'], ['r', 'distancia']) }),
      L('Campo eléctrico', 'efield', 'Una carga modifica el espacio a su alrededor: el campo eléctrico.', { req: [1], formula: F('E=k\\frac{q}{r^2}') }),
      L('Potencial eléctrico', 'elec_potential', 'Energía por unidad de carga: lo que llamamos voltaje.', { req: [2], formula: F('V=k\\frac{q}{r}') }),
      L('Corriente y ley de Ohm', 'ohm#1', 'La corriente es carga en movimiento; el voltaje la impulsa y la resistencia la limita.', { req: [3], lab: 'circuit', formula: F('V=IR', ['V', 'voltaje (V)'], ['I', 'corriente (A)'], ['R', 'resistencia (Ω)']) }),
      L('Potencia eléctrica', 'ohm#2', 'La potencia es la rapidez con que se usa energía.', { req: [4], formula: F('P=VI=I^2R=\\frac{V^2}{R}') }),
      L('Circuitos serie y paralelo', 'ohm#3', 'En serie las resistencias se suman; en paralelo se suman los inversos.', { req: [4], formula: F('R_s=R_1+R_2,\\quad \\frac1{R_p}=\\frac1{R_1}+\\frac1{R_2}') }),
      L('Capacitores', 'capacitor', 'Almacenan energía en un campo eléctrico.', { req: [3], formula: F('U=\\tfrac12CV^2') }),
      L('Proyecto: tu primer circuito', 'project:circuit', 'Serie y paralelo combinados en un circuito real.', { req: [6] }),
      L('Magnetismo', 'magnetic', 'Las cargas en movimiento sienten fuerzas magnéticas.', { req: [2], formula: F('F=qvB\\sin\\theta') }),
      L('Fuerzas magnéticas', 'magnetic', 'Motores eléctricos: corrientes que sienten fuerzas.', { req: [9] }),
      L('Inducción', 'faraday', 'Un campo magnético que cambia induce voltaje (Faraday).', { req: [9], formula: F('\\varepsilon=-N\\frac{\\Delta\\Phi}{\\Delta t}') }),
      L('Generadores y transformadores', 'faraday', 'Mover imanes cerca de bobinas produce electricidad.', { req: [11] }),
      L('Ondas electromagnéticas', 'em_wave', 'Campos que se regeneran mutuamente y viajan a la velocidad de la luz.', { req: [11], formula: F('c=f\\lambda,\\quad c=3\\times10^8\\ \\text{m/s}') }),
      L('Luz y espectro', 'em_wave', 'Radio, microondas, luz visible, rayos X: todo es la misma onda con distinta frecuencia.', { req: [13] }),
      L('Aplicación: antenas y señales', 'em_wave', 'El tamaño de una antena depende de la longitud de onda de la señal.', { req: [14] }),
      L('JEFE · Señor de la Energía', ['coulomb', 'ohm@3', 'capacitor', 'faraday', 'em_wave'], 'Cargas, circuitos, campos y ondas.', { boss: true, req: [15, 8, 12] }),
    ],
  },
  {
    id: 'ingenieria', icon: '🎓', name: 'Academia de Ingeniería', subject: 'Aplicación integrada', color: '#fde047', music: 'future',
    landmark: 'academy', pos: [0, 10, -58],
    story: 'La academia donde las regiones se reúnen. Aquí no hay un solo método correcto: hay problemas reales y modelos para resolverlos.',
    applications: ['Ingeniería civil', 'Ingeniería eléctrica', 'Mecatrónica', 'Ciencia de datos'],
    prereq: [{ r: 'fisica', n: 9 }, { r: 'calculo', n: 7 }],
    boss: { name: 'EL GRAN PROBLEMA', enemy: 'caos', lore: 'El Caos mismo se presenta como un problema abierto que combina todo lo aprendido.' },
    weapon: 'orbe',
    levels: [
      L('Modelado matemático', 'concept:eng_modeling', 'Un modelo simplifica la realidad con supuestos explícitos para poder calcular y predecir.'),
      L('Proyecto: el puente colgante', 'project:bridge', 'Álgebra, geometría, trigonometría y estática en un diseño.', { req: [1], lab: 'bridge' }),
      L('Proyecto: trayectoria', 'project:trajectory', 'Cinemática vectorial para lanzar un paquete con precisión.', { req: [1] }),
      L('Proyecto: circuito', 'project:circuit', 'Resistencias en serie y paralelo, ley de Ohm.', { req: [1] }),
      L('Proyecto: análisis de datos', 'project:data', 'Estadística aplicada a un sensor real.', { req: [1] }),
      L('Estructuras y fuerzas', ['pythag@3', 'newton@3'], 'Triángulos que soportan cargas.', { req: [2] }),
      L('Optimización de materiales', ['optimize', 'quad_area@3'], 'Máximo resultado con mínimo material.', { req: [2] }),
      L('Robot móvil', ['kinematics@3', 'vec_comp'], 'Posición y velocidad de un robot que se mueve en el plano.', { req: [3] }),
      L('Imagen digital', ['mat_vec', 'transform@3'], 'Transformar una imagen es multiplicar matrices.', { req: [3] }),
      L('Control de sistemas', ['ode_sep', 'terminal'], 'Un sistema reacciona a lo que ocurre en él: realimentación.', { req: [4] }),
      L('Energía eléctrica', ['ohm@3', 'faraday'], 'Generar, transportar y consumir energía.', { req: [4] }),
      L('Comunicaciones', ['em_wave', 'trig_graph'], 'Señales, frecuencias y antenas.', { req: [4] }),
      L('Incertidumbre y medición', ['conf_int', 'zscore'], 'Ninguna medida es exacta: se reporta con su incertidumbre.', { req: [5] }),
      L('Dinámica de sistemas', ['oscillation', 'ode2_char'], 'Vibraciones en puentes y edificios.', { req: [10] }),
      L('Diseño integrado', ['project:bridge', 'project:trajectory'], 'Varias disciplinas, un solo diseño.', { req: [6, 7, 8, 9] }),
      L('JEFE · EL GRAN PROBLEMA', ['project:bridge', 'project:circuit', 'project:trajectory', 'project:data'], 'Una misión abierta que combina todas las regiones. Hay varios caminos para resolverla.', { boss: true, req: [15, 11, 12, 13] }),
    ],
  },
];

// Ids estables, grado de dificultad por posición y metadatos derivados.
REGIONS.forEach((r, ri) => {
  r.index = ri;
  r.levels.forEach((lv, i) => {
    lv.n = i + 1;
    lv.id = `${r.id}.${i + 1}`;
    lv.region = r.id;
    lv.req = (lv.req && lv.req.length ? lv.req : i === 0 ? [] : [i]).map((n) => `${r.id}.${n}`);
    lv.baseDiff = i < 5 ? 1 : i < 11 ? 2 : 3;
    lv.app = lv.app || r.applications[i % r.applications.length];
  });
});

export const REGION_BY_ID = Object.fromEntries(REGIONS.map((r) => [r.id, r]));
export const ALL_LEVELS = REGIONS.flatMap((r) => r.levels);
export const LEVEL_BY_ID = Object.fromEntries(ALL_LEVELS.map((l) => [l.id, l]));
export const levelsOf = (regionId) => REGION_BY_ID[regionId].levels;
