// Teoremas con las 18 etapas pedagógicas: nunca una fórmula aislada.
// `viz` indica qué visualización interactiva usar (ver src/pages/viz.js).
// Las demostraciones están adaptadas por nivel: intuitiva (N1), geométrica/algebraica (N2).

export const THEOREMS = [
  {
    id: 'pitagoras', name: 'Teorema de Pitágoras', level: 'geometria.5', viz: 'pythagoras',
    historia: 'La relación entre los lados de un triángulo rectángulo se usaba mucho antes de Pitágoras: la tablilla babilónica Plimpton 322 (c. 1800 a. C.) lista ternas pitagóricas, y textos indios (Sulba Sutras) y chinos (Zhou Bi Suan Jing) la describen. La tradición griega la asocia a la escuela pitagórica (s. VI a. C.), y Euclides la demuestra en los Elementos (I.47).',
    contribuyentes: ['Escribas babilonios', 'Autores de los Sulba Sutras (India)', 'Autores del Zhoubi (China)', 'Escuela pitagórica', 'Euclides'],
    problema: '¿Cómo se relaciona la longitud de los lados de un triángulo que tiene un ángulo recto? Sirve para medir distancias que no se pueden medir directamente.',
    intuicion: 'Si construyes un cuadrado sobre cada lado del triángulo rectángulo, el área del cuadrado grande es exactamente la suma de las áreas de los dos cuadrados pequeños.',
    formula: 'a^2+b^2=c^2',
    simbolos: [['a, b', 'catetos: los dos lados que forman el ángulo recto'], ['c', 'hipotenusa: el lado opuesto al ángulo recto (siempre el más largo)'], ['²', 'elevar al cuadrado = área de un cuadrado de ese lado']],
    demostracion: [
      'Nivel intuitivo: dibuja un cuadrado grande de lado (a + b). Dentro caben 4 copias del triángulo y, al centro, un cuadrado inclinado de lado c.',
      'Área total = (a + b)² = a² + 2ab + b².',
      'También = 4·(ab/2) + c² = 2ab + c².',
      'Igualando: a² + 2ab + b² = 2ab + c², así que a² + b² = c². ∎',
    ],
    ejemplo: 'Una escalera de 5 m se apoya en una pared con el pie a 3 m. ¿A qué altura llega? 3² + h² = 5² → h² = 16 → h = 4 m.',
    guiado: 'pythag@1', individual: 'pythag@2',
    aplicacion: 'Comprobar que una esquina es “a escuadra” (terna 3-4-5), medir diagonales de pantallas, distancias en mapas y videojuegos.',
    ingenieria: 'Cálculo de longitudes de cables y tirantes en puentes, vigas diagonales en estructuras y la distancia euclidiana en robótica y gráficos.',
    errores: ['Sumar los catetos en vez de sumar sus cuadrados.', 'Usar el teorema en triángulos que NO son rectángulos (allí se usa la ley de cosenos).', 'Olvidar sacar la raíz al final.'],
    quiz: ['pythag@2', 'geo_distance@2'], desafio: 'project:bridge',
    revision: 'Dentro de 3 días: halla el lado que falta en un triángulo 8-15-17 y explica por qué la hipotenusa es la más larga.',
  },
  {
    id: 'aritmetica-fundamental', name: 'Teorema Fundamental de la Aritmética', level: 'aritmetica.5', viz: 'primes',
    historia: 'Euclides (c. 300 a. C.) demostró en los Elementos las propiedades clave de los primos; Gauss (1801) formuló y demostró con claridad la unicidad de la factorización en sus Disquisitiones Arithmeticae.',
    contribuyentes: ['Euclides', 'Carl Friedrich Gauss'],
    problema: '¿Se puede descomponer cada número entero en piezas básicas, y es única esa descomposición?',
    intuicion: 'Los primos son como los átomos: todo número se arma multiplicando primos y existe una sola receta (sin importar el orden).',
    formula: 'n=p_1^{a_1}\\cdot p_2^{a_2}\\cdots p_k^{a_k}',
    simbolos: [['n', 'un entero mayor que 1'], ['pᵢ', 'números primos distintos'], ['aᵢ', 'cuántas veces aparece cada primo']],
    demostracion: ['Existencia: si n es compuesto, n = a·b con a, b < n; repetimos con a y b hasta que todos sean primos.', 'Unicidad: si un primo p divide a un producto a·b, debe dividir a a o a b (lema de Euclides). Con eso, dos factorizaciones distintas llevarían a una contradicción. ∎'],
    ejemplo: '360 = 2³ · 3² · 5. Cualquier otra forma de escribir 360 como producto de primos es solo un reordenamiento.',
    guiado: 'prime_factors@1', individual: 'prime_factors@2',
    aplicacion: 'Simplificar fracciones, hallar MCD y MCM, y entender por qué funciona la criptografía de clave pública (factorizar es difícil).',
    ingenieria: 'La seguridad de RSA se basa en que multiplicar dos primos grandes es fácil pero factorizar el resultado es muy costoso.',
    errores: ['Considerar 1 como primo.', 'Parar la factorización antes de que todos los factores sean primos.'],
    quiz: ['gcd_lcm@2', 'prime_factors@3'], desafio: 'gcd_lcm@3',
    revision: 'Dentro de una semana: factoriza 2310 y dime cuántos divisores tiene.',
  },
  {
    id: 'formula-cuadratica', name: 'Fórmula general de la ecuación cuadrática', level: 'algebra.15', viz: 'parabola',
    historia: 'Los babilonios resolvían problemas cuadráticos hace unos 4000 años con métodos geométricos. Brahmagupta (s. VII) dio una regla general; Al-Juarismi (s. IX) la sistematizó completando el cuadrado, y Viète y Descartes la expresaron con notación simbólica.',
    contribuyentes: ['Matemáticos babilonios', 'Brahmagupta', 'Al-Juarismi', 'Viète', 'Descartes'],
    problema: 'Resolver ax² + bx + c = 0 sin tener que adivinar factores.',
    intuicion: 'Completar el cuadrado convierte la ecuación en “algo al cuadrado = número”, y de ahí se saca la raíz.',
    formula: 'x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}',
    simbolos: [['a, b, c', 'coeficientes de ax² + bx + c (a ≠ 0)'], ['b² − 4ac', 'discriminante: >0 dos soluciones reales; =0 una; <0 ninguna real'], ['±', 'dos casos: con + y con −']],
    demostracion: ['Divide entre a: x² + (b/a)x + c/a = 0.', 'Completa el cuadrado: (x + b/2a)² = (b² − 4ac)/(4a²).', 'Saca raíz: x + b/2a = ±√(b² − 4ac)/2a.', 'Despeja x. ∎'],
    ejemplo: 'x² − 5x + 6 = 0 → Δ = 25 − 24 = 1 → x = (5 ± 1)/2 → x = 3 o x = 2.',
    guiado: 'quadratic_eq@1', individual: 'quadratic_eq@3',
    aplicacion: 'Trayectorias de balones, áreas con una condición, beneficios máximos.',
    ingenieria: 'Análisis de vibraciones (raíces de la ecuación característica), óptica de espejos parabólicos y control.',
    errores: ['Olvidar el signo de −b.', 'Calcular b² − 4ac mal cuando c o a son negativos.', 'Dividir solo la raíz (y no todo el numerador) entre 2a.'],
    quiz: ['quadratic_eq@2', 'factor@2'], desafio: 'optimize',
    revision: 'Dentro de 5 días: resuelve 2x² + 3x − 2 = 0 y verifica sustituyendo.',
  },
  {
    id: 'angulos-triangulo', name: 'Suma de ángulos de un triángulo', level: 'geometria.4', viz: 'triangle-angles',
    historia: 'Aparece en los Elementos de Euclides (I.32), apoyada en el postulado de las paralelas. En geometrías no euclidianas (esfera, hiperbólica) la suma NO es 180°: descubrimiento del s. XIX (Gauss, Bolyai, Lobachevsky).',
    contribuyentes: ['Euclides', 'Gauss', 'Bolyai', 'Lobachevsky'],
    problema: '¿Qué tienen en común todos los triángulos, sin importar su forma?',
    intuicion: 'Si recortas las tres esquinas de un triángulo y las juntas, forman una línea recta (180°).',
    formula: '\\alpha+\\beta+\\gamma=180^\\circ',
    simbolos: [['α, β, γ', 'los tres ángulos interiores']],
    demostracion: ['Traza por un vértice una paralela al lado opuesto.', 'Los ángulos alternos internos son iguales.', 'Los tres ángulos del triángulo quedan juntos formando un ángulo llano (180°). ∎'],
    ejemplo: 'Si dos ángulos miden 50° y 60°, el tercero mide 180 − 110 = 70°.',
    guiado: 'triangle_angle@1', individual: 'triangle_angle@2',
    aplicacion: 'Topografía, diseño de tejados, trazado de rutas.',
    ingenieria: 'Triangulación para localizar posiciones (GPS, topografía) y diseño de armaduras.',
    errores: ['Creer que en cualquier superficie suma 180° (en una esfera es mayor).'],
    quiz: ['triangle_angle@2', 'polygon_angles@1'], desafio: 'polygon_angles@3',
    revision: 'Dentro de 4 días: usa esta regla para demostrar la suma de ángulos de un cuadrilátero (360°).',
  },
  {
    id: 'teorema-fundamental-calculo', name: 'Teorema Fundamental del Cálculo', level: 'calculo.12', viz: 'ftc',
    historia: 'Isaac Barrow, Newton y Leibniz (s. XVII) descubrieron de forma independiente que derivar e integrar son procesos inversos. Cauchy y Riemann (s. XIX) le dieron rigor. Antes, Arquímedes y matemáticos de la escuela de Kerala (Madhava) ya calculaban áreas con sumas infinitas.',
    contribuyentes: ['Arquímedes', 'Madhava', 'Isaac Barrow', 'Isaac Newton', 'Gottfried Leibniz', 'Cauchy', 'Riemann'],
    problema: '¿Cómo calcular el área bajo una curva sin sumar infinitos rectángulos?',
    intuicion: 'La integral acumula; la derivada mide la rapidez de acumulación. Acumular y medir el cambio se deshacen mutuamente.',
    formula: '\\int_a^b f(x)\\,dx=F(b)-F(a),\\quad F\'(x)=f(x)',
    simbolos: [['∫', 'suma continua (acumulación)'], ['f(x)', 'la función a acumular'], ['F(x)', 'una antiderivada de f (F′ = f)'], ['a, b', 'límites de integración']],
    demostracion: ['Define A(x) = área bajo f desde a hasta x.', 'A(x+h) − A(x) ≈ f(x)·h (una franja delgada).', 'Entonces A′(x) = f(x): el área es una antiderivada.', 'Por tanto, el área de a a b es F(b) − F(a). ∎ (versión intuitiva)'],
    ejemplo: '∫₀³ x² dx = [x³/3]₀³ = 27/3 − 0 = 9.',
    guiado: 'definite_integral@1', individual: 'definite_integral@2',
    aplicacion: 'De la velocidad se obtiene la distancia recorrida; del caudal, el volumen acumulado.',
    ingenieria: 'Cálculo de trabajo, carga total, energía y valores medios de señales.',
    errores: ['Olvidar evaluar en ambos límites.', 'Confundir una antiderivada con la función original.'],
    quiz: ['integral_poly@2', 'definite_integral@2'], desafio: 'integral_tricks',
    revision: 'Dentro de 7 días: ¿qué área hay bajo y = 2x entre 0 y 5? Verifica con un triángulo.',
  },
  {
    id: 'ley-cosenos', name: 'Ley de cosenos', level: 'trigonometria.10', viz: 'cosine-law',
    historia: 'Euclides la presenta de forma geométrica (II.12 y II.13). Al-Kashi (s. XV) la utilizó en forma trigonométrica para astronomía; por eso se le llama a veces “teorema de Al-Kashi”.',
    contribuyentes: ['Euclides', 'Al-Kashi'],
    problema: '¿Cómo hallar un lado de un triángulo cuando no es rectángulo y se conocen dos lados y el ángulo entre ellos?',
    intuicion: 'Es Pitágoras con un término de corrección que depende de cuánto se abre el ángulo: si el ángulo es recto, la corrección es cero.',
    formula: 'c^2=a^2+b^2-2ab\\cos C',
    simbolos: [['a, b', 'dos lados conocidos'], ['C', 'ángulo entre a y b'], ['c', 'el lado opuesto a C']],
    demostracion: ['Traza la altura sobre el lado a: crea dos triángulos rectángulos.', 'Aplica Pitágoras en cada uno y expresa la altura con b·sen C.', 'Al sustituir y simplificar con sen² + cos² = 1 aparece −2ab·cos C. ∎'],
    ejemplo: 'a = 7, b = 9, C = 60° → c² = 49 + 81 − 2·7·9·0,5 = 67 → c ≈ 8,19.',
    guiado: 'law_cosines', individual: 'law_cosines',
    aplicacion: 'Distancias entre dos puntos de un terreno conocidos por ángulos y rutas.',
    ingenieria: 'Cálculo de fuerzas resultantes (suma de vectores no perpendiculares) y mecanismos articulados.',
    errores: ['Usar el ángulo equivocado (debe ser el comprendido entre a y b).', 'Calculadora en radianes cuando el ángulo está en grados.'],
    quiz: ['law_cosines', 'law_sines'], desafio: 'elevation',
    revision: 'Dentro de 5 días: comprueba que con C = 90° la ley de cosenos da Pitágoras.',
  },
  {
    id: 'irracionalidad-raiz2', name: 'La irracionalidad de √2', level: 'aritmetica.15', viz: 'sqrt2',
    historia: 'La tradición atribuye el descubrimiento a la escuela pitagórica (hacia el s. V a. C.), aunque los detalles históricos son inciertos. La prueba clásica por contradicción aparece en la tradición griega y se conserva en comentarios a Euclides.',
    contribuyentes: ['Escuela pitagórica (tradición)', 'Matemáticos griegos'],
    problema: '¿Se puede escribir la diagonal de un cuadrado de lado 1 como fracción de enteros?',
    intuicion: 'Si pudiera, habría una fracción “más simple posible” que sería, a la vez, no tan simple. Esa contradicción lo prohíbe.',
    formula: '\\sqrt2\\notin\\mathbb{Q}',
    simbolos: [['√2', 'el número cuyo cuadrado es 2'], ['ℚ', 'conjunto de los números racionales (fracciones)'], ['∉', 'no pertenece a']],
    demostracion: ['Supón √2 = p/q con p/q irreducible.', 'Entonces p² = 2q², así que p² es par, luego p es par: p = 2k.', 'Entonces 4k² = 2q², o sea q² = 2k²: q también es par.', 'Pero p y q no pueden ser ambos pares si la fracción era irreducible. Contradicción. ∎'],
    ejemplo: '1,414213… nunca termina ni se repite: se puede aproximar tanto como quieras, pero no escribir exactamente como fracción.',
    guiado: 'roots@3', individual: 'classify_number',
    aplicacion: 'Diagonales de pantallas, formato de papel A4 (la razón entre lados es √2).',
    ingenieria: 'Aproximaciones numéricas y errores de redondeo en cálculo científico.',
    errores: ['Creer que un decimal largo ya es racional.', 'Confundir “infinitos decimales” con “irracional” (0,333… es racional).'],
    quiz: ['classify_number'], desafio: 'concept:infinity',
    revision: 'Dentro de 10 días: explica con tus palabras por qué la contradicción surge.',
  },
  {
    id: 'cuadrado-binomio', name: 'Cuadrado de un binomio', level: 'algebra.8', viz: 'binomial-square',
    historia: 'Los Elementos de Euclides (II.4) lo enuncian geométricamente: un cuadrado de lado (a + b) se descompone en dos cuadrados y dos rectángulos. Al-Juarismi usó figuras similares para resolver ecuaciones.',
    contribuyentes: ['Euclides', 'Al-Juarismi'],
    problema: '¿Por qué (a + b)² no es a² + b²?',
    intuicion: 'Un cuadrado de lado a + b se divide en un cuadrado a², un cuadrado b² y DOS rectángulos a·b.',
    formula: '(a+b)^2=a^2+2ab+b^2',
    simbolos: [['a, b', 'cualquier número o expresión'], ['2ab', 'las dos piezas rectangulares que suelen olvidarse']],
    demostracion: ['(a + b)(a + b) = a·a + a·b + b·a + b·b.', 'Agrupando: a² + 2ab + b². ∎'],
    ejemplo: '(x + 3)² = x² + 6x + 9. Con x = 2: 25 = 4 + 12 + 9 ✓.',
    guiado: 'notable_prod@1', individual: 'notable_prod@2',
    aplicacion: 'Cálculo mental de cuadrados: 51² = (50 + 1)² = 2500 + 100 + 1.',
    ingenieria: 'Aparece en la varianza, la energía cinética relativa y el análisis de errores.',
    errores: ['Escribir (a + b)² = a² + b².'],
    quiz: ['notable_prod@2', 'factor@2'], desafio: 'factor@3',
    revision: 'Dentro de 4 días: calcula 103² mentalmente con este patrón.',
  },
  {
    id: 'conservacion-energia', name: 'Conservación de la energía mecánica', level: 'fisica.10', viz: 'energy',
    historia: 'Se fue formulando durante el s. XIX (Joule, Mayer, Helmholtz, Kelvin) tras siglos de ideas previas (Leibniz y la vis viva). Es un principio que surge de la simetría temporal: Emmy Noether (1918) mostró la conexión matemática.',
    contribuyentes: ['Leibniz', 'Joule', 'Mayer', 'Helmholtz', 'Emmy Noether'],
    problema: '¿Cómo predecir la velocidad de un objeto sin analizar cada instante del movimiento?',
    intuicion: 'La energía solo cambia de forma: lo que pierde en altura lo gana en velocidad (si no hay rozamiento).',
    formula: 'mgh_1+\\tfrac12mv_1^2=mgh_2+\\tfrac12mv_2^2',
    simbolos: [['m', 'masa'], ['g', 'aceleración de la gravedad (9,8 m/s²)'], ['h', 'altura'], ['v', 'velocidad']],
    demostracion: ['Para caída libre: v² = v₀² + 2g(h₁ − h₂).', 'Multiplica por m/2 y reordena: ½mv₂² − ½mv₁² = mg(h₁ − h₂). ∎'],
    ejemplo: 'Un objeto cae 20 m: v = √(2·9,8·20) ≈ 19,8 m/s.',
    guiado: 'work_energy#4@1', individual: 'work_energy#4@2',
    aplicacion: 'Montañas rusas, péndulos, rebotes de pelotas.',
    ingenieria: 'Diseño de turbinas hidroeléctricas, frenos regenerativos y almacenamiento de energía.',
    errores: ['Olvidar que con rozamiento parte de la energía se transforma en calor.', 'Usar la masa en la velocidad final (se cancela).'],
    quiz: ['work_energy@3', 'projectile'], desafio: 'project:trajectory',
    revision: 'Dentro de 6 días: ¿desde qué altura debe soltarse algo para llegar a 10 m/s?',
  },
  {
    id: 'infinitud-primos', name: 'Infinitud de los números primos', level: 'aritmetica.5', viz: 'primes',
    historia: 'Euclides la demostró en los Elementos (IX.20), hacia el 300 a. C. La prueba sigue siendo un modelo de elegancia matemática.',
    contribuyentes: ['Euclides'],
    problema: '¿Se acaban alguna vez los números primos?',
    intuicion: 'Si hubiera una lista finita de primos, podrías fabricar un número nuevo que ninguno de ellos divide.',
    formula: 'N=p_1p_2\\cdots p_n+1',
    simbolos: [['p₁…pₙ', 'la supuesta lista completa de primos'], ['N', 'número construido con esa lista']],
    demostracion: ['Supón que p₁, …, pₙ son todos los primos.', 'Sea N = p₁·p₂·…·pₙ + 1. Ninguno de los pᵢ divide a N (deja resto 1).', 'Pero N tiene algún factor primo, que no está en la lista. Contradicción. ∎'],
    ejemplo: '2·3·5·7·11·13 + 1 = 30031 = 59·509: los primos 59 y 509 no estaban en la lista inicial.',
    guiado: 'prime_factors@2', individual: 'prime_factors@3',
    aplicacion: 'Siempre habrá primos más grandes para la criptografía.',
    ingenieria: 'Generación de claves criptográficas.',
    errores: ['Creer que N es siempre primo (no: 30031 es compuesto).'],
    quiz: ['divisibility@2', 'prime_factors@2'], desafio: 'gcd_lcm@3',
    revision: 'Dentro de 8 días: explica por qué N deja resto 1 al dividirlo entre cualquier pᵢ.',
  },
];

export const THEOREM_BY_ID = Object.fromEntries(THEOREMS.map((t) => [t.id, t]));
export const THEOREMS_FOR_LEVEL = (levelId) => THEOREMS.filter((t) => t.level === levelId);
